/* More components for the Architecture Lab: cloud services (AWS, Google Cloud, Azure), containers and Kubernetes, DevOps tools, and common software.
 * Every capacity, latency and price here is a round TEACHING number, not a provider's price list or benchmark.
 * `prov` is where the component comes from; `eq` groups equivalent services so a design can be moved between clouds.
 * Behaviour comes from `cls` (see sim.js): service, router, proxy, cache, queue, db, store, cdn, limiter, external, pool, passive.
 */
(function (root, factory) {
  const items = factory();
  if (typeof module === "object" && module.exports) module.exports = items;
  if (root && root.LabSim && root.LabSim.extend) root.LabSim.extend(items);
})(typeof self !== "undefined" ? self : this, function () {
  "use strict";
  const out = [];
  // shorthand: [id, name, category, icon, cls, provider, equivalence group, options]
  const add = (id, name, cat, icon, cls, prov, eq, o) => out.push(Object.assign({ id, name, cat, icon, cls, prov, eq: eq || "", cap: 0, ms: 1, cost: 0 }, o || {}));
  const svc = (cap, ms, cost, x) => Object.assign({ cap, ms, cost }, x || {});
  const dbo = (rd, wr, msR, msW, cost, rep, x) => Object.assign({ rd, wr, msR, msW, cost, rep }, x || {});

  // ------------------------------------------------------------------ AWS
  const A = "aws";
  add("ec2", "EC2 instance", "Compute", "🟧", "service", A, "vm", svc(400, 25, 80));
  add("lambda", "Lambda", "Compute", "λ", "service", A, "fn", svc(1000, 60, 100, { auto: true }));
  add("fargate", "ECS / Fargate task", "Compute", "🐳", "service", A, "container", svc(350, 30, 90));
  add("beanstalk", "Elastic Beanstalk", "Compute", "🌱", "service", A, "paas", svc(400, 28, 95));
  add("apprunner", "App Runner", "Compute", "🏃", "service", A, "paas-auto", svc(600, 35, 90, { auto: true }));
  add("awsbatch", "AWS Batch job", "Compute", "🧺", "service", A, "batch", svc(80, 400, 90));
  add("stepfn", "Step Functions", "Compute", "🪜", "service", A, "workflow", svc(200, 80, 60));
  add("eks", "EKS node group", "Containers & Kubernetes", "☸️", "pool", A, "k8s-pool", { cost: 150, podsPerNode: 8 });
  add("asg", "EC2 Auto Scaling group", "Compute", "📈", "pool", A, "asg", { cost: 80, podsPerNode: 1 });
  add("alb", "Application Load Balancer", "Traffic & edge", "⚖️", "router", A, "lb7", svc(40000, 2, 40, { ha: true }));
  add("nlb", "Network Load Balancer", "Traffic & edge", "⚖️", "router", A, "lb4", svc(100000, 1, 35, { ha: true }));
  add("apigw-aws", "API Gateway (AWS)", "Traffic & edge", "🚪", "proxy", A, "apigw", svc(10000, 5, 70));
  add("cloudfront", "CloudFront", "Traffic & edge", "🌐", "cdn", A, "cdn", svc(600000, 8, 200));
  add("route53", "Route 53", "Traffic & edge", "📖", "router", A, "dns", svc(500000, 4, 20));
  add("waf-aws", "AWS WAF", "Traffic & edge", "🛡️", "limiter", A, "waf", svc(200000, 3, 60, { waf: true }));
  add("shield", "AWS Shield", "Traffic & edge", "🛡️", "limiter", A, "ddos", svc(500000, 1, 100, { waf: true }));
  add("globalaccel", "Global Accelerator", "Traffic & edge", "🚀", "router", A, "anycast", svc(300000, 3, 90, { ha: true }));
  add("s3", "S3", "Storage", "🪣", "store", A, "object", dbo(25000, 5000, 25, 40, 100, 0));
  add("efs", "EFS", "Storage", "📁", "store", A, "filestore", dbo(5000, 2000, 10, 15, 120, 0));
  add("ebs", "EBS volume", "Storage", "💽", "store", A, "blockstore", dbo(6000, 3000, 2, 3, 80, 0));
  add("rds", "RDS (PostgreSQL/MySQL)", "Storage", "🗄️", "db", A, "sql", dbo(2000, 1000, 8, 12, 300, 200));
  add("aurora", "Aurora", "Storage", "🌅", "db", A, "sql-cloud", dbo(5000, 2500, 6, 9, 450, 250));
  add("dynamodb-aws", "DynamoDB", "Storage", "⚡", "db", A, "nosql-managed", dbo(12000, 6000, 5, 8, 450, 0));
  add("documentdb", "DocumentDB", "Storage", "📄", "db", A, "document", dbo(5000, 2500, 6, 9, 380, 260));
  add("keyspaces", "Keyspaces", "Storage", "🔑", "db", A, "wide-column", dbo(8000, 8000, 6, 5, 420, 280));
  add("neptune", "Neptune (graph)", "Storage", "🕸️", "db", A, "graph", dbo(1500, 500, 12, 20, 500, 300));
  add("timestream", "Timestream", "Storage", "⏱️", "db", A, "timeseries", dbo(4000, 12000, 15, 6, 350, 0));
  add("redshift", "Redshift", "Data & analytics", "🏭", "db", A, "warehouse", dbo(400, 2000, 300, 10, 900, 0));
  add("athena", "Athena", "Data & analytics", "🔍", "db", A, "query-lake", dbo(200, 100, 800, 50, 120, 0));
  add("elasticache", "ElastiCache (Redis)", "Storage", "⚡", "cache", A, "redis", svc(60000, 1.5, 90, { hit: 0.8 }));
  add("memorydb", "MemoryDB", "Storage", "🧠", "cache", A, "redis-durable", svc(60000, 1.5, 140, { hit: 0.8 }));
  add("sqs-aws", "SQS", "Messaging", "📭", "queue", A, "queue", svc(500, 5, 40, { unit: 40 }));
  add("sns", "SNS", "Messaging", "📣", "queue", A, "pubsub", svc(1500, 5, 50, { unit: 50 }));
  add("kinesis", "Kinesis", "Messaging", "🌊", "queue", A, "stream", svc(1200, 5, 160, { unit: 120 }));
  add("msk", "MSK (Kafka)", "Messaging", "🧵", "queue", A, "kafka", svc(1500, 5, 200, { unit: 150 }));
  add("amazonmq", "Amazon MQ (RabbitMQ)", "Messaging", "🐇", "queue", A, "rabbit", svc(450, 3, 55, { unit: 55 }));
  add("eventbridge", "EventBridge", "Messaging", "🚌", "queue", A, "eventbus", svc(1000, 6, 50, { unit: 40 }));
  add("opensearch-aws", "OpenSearch Service", "Storage", "🔎", "db", A, "search", dbo(2500, 800, 18, 15, 420, 280));
  add("bedrock", "Bedrock (LLM API)", "AI & ML", "🪨", "service", A, "llm-api", svc(30, 900, 800));
  add("sagemaker", "SageMaker endpoint", "AI & ML", "🧪", "service", A, "ml-serve", svc(40, 200, 700));
  add("cognito", "Cognito", "Security & identity", "🪪", "service", A, "idp", svc(800, 20, 60));
  add("kms-aws", "KMS", "Security & identity", "🔐", "external", A, "kms", svc(5000, 5, 0));
  add("secretsmanager", "Secrets Manager", "Security & identity", "🗝️", "passive", A, "secrets", { cost: 30, tag: "secrets" });
  add("iam", "IAM", "Security & identity", "🆔", "passive", A, "iam", { cost: 0, tag: "iam" });
  add("cloudwatch", "CloudWatch", "Observability", "📈", "passive", A, "monitoring", { cost: 60, tag: "monitoring", monitor: true });
  add("cloudwatch-alarms", "CloudWatch Alarms", "Observability", "🚨", "passive", A, "alerting", { cost: 10, tag: "alerting", monitor: true });
  add("xray", "X-Ray", "Observability", "🩻", "passive", A, "tracing", { cost: 40, tag: "tracing" });
  add("cloudtrail", "CloudTrail", "Observability", "📜", "passive", A, "audit", { cost: 20, tag: "logging" });
  add("codepipeline", "CodePipeline", "DevOps & CI/CD", "🔧", "passive", A, "cicd", { cost: 30, tag: "cicd" });
  add("codebuild", "CodeBuild", "DevOps & CI/CD", "🏗️", "passive", A, "build", { cost: 40, tag: "cicd" });
  add("codedeploy", "CodeDeploy", "DevOps & CI/CD", "🚚", "passive", A, "deploy", { cost: 20, tag: "cicd" });
  add("ecr", "ECR", "DevOps & CI/CD", "📦", "passive", A, "registry", { cost: 20, tag: "registry" });
  add("cloudformation", "CloudFormation", "DevOps & CI/CD", "📐", "passive", A, "iac-cloud", { cost: 0, tag: "iac" });

  // ------------------------------------------------------------------ Google Cloud
  const Gc = "gcp";
  add("gce", "Compute Engine VM", "Compute", "🟦", "service", Gc, "vm", svc(400, 25, 80));
  add("cloudrun", "Cloud Run", "Compute", "🏃", "service", Gc, "paas-auto", svc(800, 40, 85, { auto: true }));
  add("gcf", "Cloud Functions", "Compute", "λ", "service", Gc, "fn", svc(1000, 60, 100, { auto: true }));
  add("appengine", "App Engine", "Compute", "🏢", "service", Gc, "paas", svc(400, 28, 95, { auto: true }));
  add("gcpbatch", "Cloud Batch job", "Compute", "🧺", "service", Gc, "batch", svc(80, 400, 90));
  add("workflows-gcp", "Workflows", "Compute", "🪜", "service", Gc, "workflow", svc(200, 80, 60));
  add("gke", "GKE node pool", "Containers & Kubernetes", "☸️", "pool", Gc, "k8s-pool", { cost: 150, podsPerNode: 8 });
  add("mig", "Managed instance group", "Compute", "📈", "pool", Gc, "asg", { cost: 80, podsPerNode: 1 });
  add("cloudlb", "Cloud Load Balancing", "Traffic & edge", "⚖️", "router", Gc, "lb7", svc(60000, 2, 40, { ha: true }));
  add("cloudlb-net", "Network Load Balancer (GCP)", "Traffic & edge", "⚖️", "router", Gc, "lb4", svc(100000, 1, 35, { ha: true }));
  add("apigee", "Apigee / API Gateway", "Traffic & edge", "🚪", "proxy", Gc, "apigw", svc(10000, 5, 80));
  add("cloudcdn", "Cloud CDN", "Traffic & edge", "🌐", "cdn", Gc, "cdn", svc(600000, 8, 190));
  add("clouddns", "Cloud DNS", "Traffic & edge", "📖", "router", Gc, "dns", svc(500000, 4, 20));
  add("cloudarmor", "Cloud Armor", "Traffic & edge", "🛡️", "limiter", Gc, "waf", svc(200000, 3, 60, { waf: true }));
  add("gcs", "Cloud Storage", "Storage", "🪣", "store", Gc, "object", dbo(25000, 5000, 25, 40, 100, 0));
  add("filestore", "Filestore", "Storage", "📁", "store", Gc, "filestore", dbo(5000, 2000, 10, 15, 120, 0));
  add("persistentdisk", "Persistent Disk", "Storage", "💽", "store", Gc, "blockstore", dbo(6000, 3000, 2, 3, 80, 0));
  add("cloudsql", "Cloud SQL", "Storage", "🗄️", "db", Gc, "sql", dbo(2000, 1000, 8, 12, 300, 200));
  add("alloydb", "AlloyDB", "Storage", "🌅", "db", Gc, "sql-cloud", dbo(5000, 2500, 6, 9, 450, 250));
  add("spanner", "Spanner", "Storage", "🌍", "db", Gc, "newsql", dbo(10000, 5000, 8, 15, 900, 0));
  add("bigtable", "Bigtable", "Storage", "🧱", "db", Gc, "wide-column", dbo(20000, 10000, 5, 5, 700, 0));
  add("firestore", "Firestore", "Storage", "🔥", "db", Gc, "document", dbo(6000, 3000, 8, 12, 350, 0));
  add("memorystore", "Memorystore (Redis)", "Storage", "⚡", "cache", Gc, "redis", svc(60000, 1.5, 90, { hit: 0.8 }));
  add("bigquery", "BigQuery", "Data & analytics", "🏭", "db", Gc, "warehouse", dbo(400, 2000, 300, 10, 900, 0));
  add("dataflow", "Dataflow", "Data & analytics", "🌊", "service", Gc, "stream-proc", svc(300, 100, 200));
  add("gcppubsub", "Pub/Sub (GCP)", "Messaging", "📣", "queue", Gc, "pubsub", svc(1500, 5, 50, { unit: 50 }));
  add("cloudtasks", "Cloud Tasks", "Messaging", "📭", "queue", Gc, "queue", svc(500, 5, 40, { unit: 40 }));
  add("eventarc", "Eventarc", "Messaging", "🚌", "queue", Gc, "eventbus", svc(1000, 6, 50, { unit: 40 }));
  add("vertex", "Vertex AI endpoint", "AI & ML", "🧪", "service", Gc, "ml-serve", svc(40, 200, 700));
  add("gemini", "Gemini API", "AI & ML", "✨", "service", Gc, "llm-api", svc(30, 900, 800));
  add("identityplatform", "Identity Platform", "Security & identity", "🪪", "service", Gc, "idp", svc(800, 20, 60));
  add("cloudkms", "Cloud KMS", "Security & identity", "🔐", "external", Gc, "kms", svc(5000, 5, 0));
  add("secretmanager", "Secret Manager", "Security & identity", "🗝️", "passive", Gc, "secrets", { cost: 30, tag: "secrets" });
  add("cloudmonitoring", "Cloud Monitoring", "Observability", "📈", "passive", Gc, "monitoring", { cost: 60, tag: "monitoring", monitor: true });
  add("cloudalerting", "Cloud Alerting", "Observability", "🚨", "passive", Gc, "alerting", { cost: 10, tag: "alerting", monitor: true });
  add("cloudtrace", "Cloud Trace", "Observability", "🩻", "passive", Gc, "tracing", { cost: 40, tag: "tracing" });
  add("cloudlogging", "Cloud Logging", "Observability", "📜", "passive", Gc, "logging", { cost: 50, tag: "logging" });
  add("cloudbuild", "Cloud Build", "DevOps & CI/CD", "🏗️", "passive", Gc, "cicd", { cost: 40, tag: "cicd" });
  add("clouddeploy", "Cloud Deploy", "DevOps & CI/CD", "🚚", "passive", Gc, "deploy", { cost: 20, tag: "cicd" });
  add("artifactregistry", "Artifact Registry", "DevOps & CI/CD", "📦", "passive", Gc, "registry", { cost: 20, tag: "registry" });
  add("deploymentmanager", "Deployment Manager", "DevOps & CI/CD", "📐", "passive", Gc, "iac-cloud", { cost: 0, tag: "iac" });

  // ------------------------------------------------------------------ Azure
  const Z = "azure";
  add("azvm", "Virtual Machine", "Compute", "🟦", "service", Z, "vm", svc(400, 25, 80));
  add("appservice", "App Service", "Compute", "🏢", "service", Z, "paas", svc(400, 28, 95, { auto: true }));
  add("azfunctions", "Azure Functions", "Compute", "λ", "service", Z, "fn", svc(1000, 60, 100, { auto: true }));
  add("containerapps", "Container Apps", "Compute", "🏃", "service", Z, "paas-auto", svc(700, 38, 88, { auto: true }));
  add("aci", "Container Instances", "Compute", "🐳", "service", Z, "container", svc(350, 30, 90));
  add("azbatch", "Azure Batch job", "Compute", "🧺", "service", Z, "batch", svc(80, 400, 90));
  add("logicapps", "Logic Apps", "Compute", "🪜", "service", Z, "workflow", svc(200, 80, 60));
  add("aks", "AKS node pool", "Containers & Kubernetes", "☸️", "pool", Z, "k8s-pool", { cost: 150, podsPerNode: 8 });
  add("vmss", "VM Scale Set", "Compute", "📈", "pool", Z, "asg", { cost: 80, podsPerNode: 1 });
  add("appgw", "Application Gateway", "Traffic & edge", "⚖️", "router", Z, "lb7", svc(40000, 2, 45, { ha: true }));
  add("azlb", "Azure Load Balancer", "Traffic & edge", "⚖️", "router", Z, "lb4", svc(100000, 1, 35, { ha: true }));
  add("apim", "API Management", "Traffic & edge", "🚪", "proxy", Z, "apigw", svc(10000, 5, 90));
  add("frontdoor", "Front Door (CDN)", "Traffic & edge", "🌐", "cdn", Z, "cdn", svc(600000, 8, 200));
  add("trafficmanager", "Traffic Manager", "Traffic & edge", "📖", "router", Z, "dns", svc(500000, 4, 20));
  add("azwaf", "Azure WAF", "Traffic & edge", "🛡️", "limiter", Z, "waf", svc(200000, 3, 60, { waf: true }));
  add("blob", "Blob Storage", "Storage", "🪣", "store", Z, "object", dbo(25000, 5000, 25, 40, 100, 0));
  add("azfiles", "Azure Files", "Storage", "📁", "store", Z, "filestore", dbo(5000, 2000, 10, 15, 120, 0));
  add("azdisk", "Managed Disk", "Storage", "💽", "store", Z, "blockstore", dbo(6000, 3000, 2, 3, 80, 0));
  add("azuresql", "Azure SQL", "Storage", "🗄️", "db", Z, "sql", dbo(2000, 1000, 8, 12, 320, 200));
  add("azpostgres", "Azure Database for PostgreSQL", "Storage", "🐘", "db", Z, "sql-cloud", dbo(2200, 1000, 8, 12, 300, 200));
  add("cosmos", "Cosmos DB", "Storage", "🪐", "db", Z, "nosql-managed", dbo(10000, 5000, 6, 9, 500, 0));
  add("azredis", "Azure Cache for Redis", "Storage", "⚡", "cache", Z, "redis", svc(60000, 1.5, 90, { hit: 0.8 }));
  add("synapse", "Synapse Analytics", "Data & analytics", "🏭", "db", Z, "warehouse", dbo(400, 2000, 300, 10, 900, 0));
  add("servicebus", "Service Bus", "Messaging", "📭", "queue", Z, "queue", svc(500, 5, 45, { unit: 45 }));
  add("eventhubs", "Event Hubs", "Messaging", "🌊", "queue", Z, "stream", svc(1200, 5, 160, { unit: 120 }));
  add("eventgrid", "Event Grid", "Messaging", "🚌", "queue", Z, "eventbus", svc(1000, 6, 50, { unit: 40 }));
  add("azopenai", "Azure OpenAI", "AI & ML", "🧠", "service", Z, "llm-api", svc(30, 900, 800));
  add("azureml", "Azure ML endpoint", "AI & ML", "🧪", "service", Z, "ml-serve", svc(40, 200, 700));
  add("entraid", "Entra ID", "Security & identity", "🪪", "service", Z, "idp", svc(800, 20, 60));
  add("keyvault", "Key Vault", "Security & identity", "🗝️", "passive", Z, "secrets", { cost: 30, tag: "secrets" });
  add("azmonitor", "Azure Monitor", "Observability", "📈", "passive", Z, "monitoring", { cost: 60, tag: "monitoring", monitor: true });
  add("azalerts", "Azure Alerts", "Observability", "🚨", "passive", Z, "alerting", { cost: 10, tag: "alerting", monitor: true });
  add("appinsights", "Application Insights", "Observability", "🩻", "passive", Z, "tracing", { cost: 40, tag: "tracing" });
  add("azdevops", "Azure DevOps Pipelines", "DevOps & CI/CD", "🔧", "passive", Z, "cicd", { cost: 30, tag: "cicd" });
  add("acr", "Container Registry (ACR)", "DevOps & CI/CD", "📦", "passive", Z, "registry", { cost: 20, tag: "registry" });
  add("bicep", "Bicep / ARM", "DevOps & CI/CD", "📐", "passive", Z, "iac-cloud", { cost: 0, tag: "iac" });

  // ------------------------------------------------------------------ Docker and Kubernetes
  add("docker", "Docker container", "Containers & Kubernetes", "🐳", "service", "docker", "container", svc(300, 25, 40));
  add("dockerhost", "Docker host (VM)", "Containers & Kubernetes", "🖥️", "pool", "docker", "asg", { cost: 120, podsPerNode: 6 });
  add("swarm", "Docker Swarm nodes", "Containers & Kubernetes", "🐝", "pool", "docker", "asg", { cost: 110, podsPerNode: 6 });
  add("dockerregistry", "Container registry", "Containers & Kubernetes", "📦", "passive", "docker", "registry", { cost: 20, tag: "registry" });
  add("compose", "Docker Compose file", "Containers & Kubernetes", "📄", "passive", "docker", "iac-local", { cost: 0, tag: "iac" });
  add("k8sdeploy", "Deployment (pods)", "Containers & Kubernetes", "☸️", "service", "k8s", "container", svc(400, 25, 25, { pod: true }));
  add("k8ssts", "StatefulSet", "Containers & Kubernetes", "☸️", "service", "k8s", "", svc(300, 30, 30, { pod: true }));
  add("k8sds", "DaemonSet", "Containers & Kubernetes", "☸️", "service", "k8s", "", svc(600, 10, 10, { pod: true }));
  add("k8sjob", "Job / CronJob", "Containers & Kubernetes", "⏰", "service", "k8s", "batch", svc(80, 400, 25, { pod: true }));
  add("k8ssvc", "Service (ClusterIP)", "Containers & Kubernetes", "🔀", "router", "k8s", "", svc(100000, 1, 0));
  add("k8singress", "Ingress controller", "Containers & Kubernetes", "↘️", "proxy", "k8s", "ingress", svc(20000, 2, 40));
  add("k8snodepool", "Node pool", "Containers & Kubernetes", "🧱", "pool", "k8s", "k8s-pool", { cost: 150, podsPerNode: 8 });
  add("k8scp", "Control plane", "Containers & Kubernetes", "🎛️", "passive", "k8s", "", { cost: 75, tag: "k8s-cp" });
  add("k8shpa", "HorizontalPodAutoscaler", "Containers & Kubernetes", "📈", "passive", "k8s", "", { cost: 0, tag: "hpa" });
  add("k8spvc", "PersistentVolume", "Containers & Kubernetes", "💽", "store", "k8s", "blockstore", dbo(6000, 3000, 2, 3, 80, 0));
  add("k8sconfig", "ConfigMap", "Containers & Kubernetes", "🧾", "passive", "k8s", "", { cost: 0, tag: "config" });
  add("k8ssecret", "Secret", "Containers & Kubernetes", "🗝️", "passive", "k8s", "secrets", { cost: 0, tag: "secrets" });
  add("istio", "Istio service mesh", "Containers & Kubernetes", "🕸️", "proxy", "k8s", "mesh", svc(20000, 3, 80));
  add("linkerd", "Linkerd", "Containers & Kubernetes", "🔗", "proxy", "k8s", "mesh", svc(25000, 2, 60));
  add("helm", "Helm chart", "Containers & Kubernetes", "⛵", "passive", "k8s", "", { cost: 0, tag: "iac" });
  add("argocd", "Argo CD (GitOps)", "DevOps & CI/CD", "🐙", "passive", "k8s", "", { cost: 0, tag: "gitops" });

  // ------------------------------------------------------------------ DevOps tools
  const D = "devops";
  add("githubactions", "GitHub Actions", "DevOps & CI/CD", "🐙", "passive", D, "cicd", { cost: 30, tag: "cicd" });
  add("jenkins", "Jenkins", "DevOps & CI/CD", "🤵", "passive", D, "cicd", { cost: 60, tag: "cicd" });
  add("gitlabci", "GitLab CI", "DevOps & CI/CD", "🦊", "passive", D, "cicd", { cost: 40, tag: "cicd" });
  add("circleci", "CircleCI", "DevOps & CI/CD", "⭕", "passive", D, "cicd", { cost: 40, tag: "cicd" });
  add("terraform", "Terraform", "DevOps & CI/CD", "🏗️", "passive", D, "iac", { cost: 0, tag: "iac" });
  add("ansible", "Ansible", "DevOps & CI/CD", "🅰️", "passive", D, "iac", { cost: 0, tag: "iac" });
  add("pulumi", "Pulumi", "DevOps & CI/CD", "🧩", "passive", D, "iac", { cost: 0, tag: "iac" });
  add("artifactory", "Artifactory / Nexus", "DevOps & CI/CD", "📦", "passive", D, "registry", { cost: 40, tag: "registry" });
  add("sonarqube", "SonarQube", "DevOps & CI/CD", "🧪", "passive", D, "", { cost: 30, tag: "quality" });
  add("trivy", "Trivy / image scanning", "DevOps & CI/CD", "🔬", "passive", D, "", { cost: 0, tag: "security-scan" });
  add("launchdarkly", "Feature flags", "DevOps & CI/CD", "🚩", "passive", D, "", { cost: 40, tag: "flags" });
  add("prometheus", "Prometheus", "Observability", "🔥", "passive", D, "monitoring", { cost: 40, tag: "monitoring", monitor: true });
  add("grafana", "Grafana", "Observability", "📊", "passive", D, "dashboards", { cost: 20, tag: "monitoring", monitor: true });
  add("alertmanager", "Alertmanager", "Observability", "🚨", "passive", D, "alerting", { cost: 10, tag: "alerting", monitor: true });
  add("pagerduty", "PagerDuty / on-call", "Observability", "📟", "passive", D, "alerting", { cost: 30, tag: "alerting", monitor: true });
  add("datadog", "Datadog", "Observability", "🐶", "passive", D, "monitoring", { cost: 120, tag: "monitoring", monitor: true });
  add("elk", "ELK / OpenSearch logs", "Observability", "📜", "passive", D, "logging", { cost: 90, tag: "logging" });
  add("otel", "OpenTelemetry", "Observability", "🩻", "passive", D, "tracing", { cost: 10, tag: "tracing" });
  add("sentry", "Sentry (errors)", "Observability", "🛰️", "passive", D, "", { cost: 30, tag: "errors" });
  add("vault", "HashiCorp Vault", "Security & identity", "🔐", "passive", D, "secrets", { cost: 40, tag: "secrets" });

  // ------------------------------------------------------------------ common software
  const O = "oss";
  add("springboot", "Spring Boot service", "Compute", "🍃", "service", O, "", svc(500, 22, 90));
  add("dotnet", ".NET service", "Compute", "🟪", "service", O, "", svc(500, 22, 85));
  add("rails", "Ruby on Rails", "Compute", "💎", "service", O, "", svc(200, 35, 65));
  add("django", "Django", "Compute", "🌿", "service", O, "", svc(250, 30, 65));
  add("fastapi", "FastAPI", "Compute", "⚡", "service", O, "", svc(500, 15, 65));
  add("nestjs", "NestJS", "Compute", "🐈", "service", O, "", svc(450, 20, 70));
  add("laravel", "Laravel / PHP", "Compute", "🐘", "service", O, "", svc(220, 35, 60));
  add("rustsvc", "Rust service", "Compute", "🦀", "service", O, "", svc(1500, 6, 70));
  add("elixir", "Elixir / Phoenix", "Compute", "💧", "service", O, "", svc(1200, 8, 70));
  add("kotlin", "Kotlin service", "Compute", "🟣", "service", O, "", svc(550, 20, 90));
  add("grpcsvc", "gRPC service", "Compute", "📡", "service", O, "", svc(900, 10, 75));
  add("bff", "Backend for frontend", "Compute", "🧩", "service", O, "", svc(600, 15, 70));
  add("graphql", "GraphQL gateway", "Traffic & edge", "◼️", "proxy", O, "", svc(8000, 6, 70));
  add("wsgateway", "WebSocket gateway", "Traffic & edge", "🔌", "proxy", O, "", svc(10000, 3, 70));
  add("traefik", "Traefik", "Traffic & edge", "🔀", "proxy", O, "", svc(25000, 1.5, 35));
  add("caddy", "Caddy", "Traffic & edge", "🟩", "proxy", O, "", svc(20000, 1.5, 30));
  add("kong", "Kong", "Traffic & edge", "🦍", "proxy", O, "apigw", svc(15000, 4, 80));
  add("varnish", "Varnish cache", "Storage", "🧊", "cache", O, "", svc(100000, 1, 90, { hit: 0.7 }));
  add("redis-cluster", "Redis Cluster", "Storage", "⚡", "cache", O, "redis", svc(200000, 1.5, 300, { hit: 0.85 }));
  add("hazelcast", "Hazelcast", "Storage", "💠", "cache", O, "", svc(80000, 1.5, 120, { hit: 0.8 }));
  add("mariadb", "MariaDB", "Storage", "🐬", "db", O, "sql", dbo(2000, 900, 8, 12, 270, 180));
  add("oracle", "Oracle Database", "Storage", "🔴", "db", O, "", dbo(2500, 1200, 8, 12, 900, 500));
  add("sqlserver", "SQL Server", "Storage", "🟥", "db", O, "sql", dbo(2200, 1000, 8, 12, 500, 300));
  add("sqlite", "SQLite (single file)", "Storage", "🪶", "db", O, "", dbo(500, 200, 2, 4, 10, 0));
  add("cockroach", "CockroachDB", "Storage", "🪳", "db", O, "newsql", dbo(6000, 3000, 8, 14, 550, 300));
  add("yugabyte", "YugabyteDB", "Storage", "🟠", "db", O, "newsql", dbo(6000, 3000, 8, 14, 500, 280));
  add("tidb", "TiDB", "Storage", "🐯", "db", O, "newsql", dbo(6000, 3000, 8, 14, 500, 280));
  add("scylla", "ScyllaDB", "Storage", "🦑", "db", O, "wide-column", dbo(15000, 12000, 4, 4, 450, 300));
  add("neo4j", "Neo4j", "Storage", "🕸️", "db", O, "graph", dbo(1500, 500, 12, 20, 500, 300));
  add("influx", "InfluxDB", "Storage", "⏱️", "db", O, "timeseries", dbo(5000, 20000, 10, 4, 300, 0));
  add("timescale", "TimescaleDB", "Storage", "⏳", "db", O, "timeseries", dbo(4000, 8000, 10, 6, 320, 200));
  add("elasticsearch", "Elasticsearch", "Storage", "🔎", "db", O, "search", dbo(2500, 800, 18, 15, 420, 280));
  add("solr", "Solr", "Storage", "☀️", "db", O, "search", dbo(2500, 700, 20, 16, 380, 250));
  add("meilisearch", "Meilisearch", "Storage", "🔍", "db", O, "search", dbo(3000, 500, 8, 12, 200, 150));
  add("pinecone", "Pinecone", "AI & ML", "🌲", "db", O, "vector", dbo(1500, 400, 15, 25, 500, 150));
  add("weaviate", "Weaviate", "AI & ML", "🧬", "db", O, "vector", dbo(1500, 400, 15, 25, 450, 150));
  add("qdrant", "Qdrant", "AI & ML", "🧭", "db", O, "vector", dbo(1800, 500, 12, 20, 400, 150));
  add("milvus", "Milvus", "AI & ML", "🐬", "db", O, "vector", dbo(2000, 500, 14, 22, 450, 160));
  add("pgvector", "pgvector (PostgreSQL)", "AI & ML", "🐘", "db", O, "vector", dbo(1200, 600, 18, 20, 320, 200));
  add("mlserver", "Model server (Triton / TorchServe)", "AI & ML", "🤖", "service", O, "ml-serve", svc(60, 120, 600));
  add("vllm", "vLLM / TGI (self-hosted LLM)", "AI & ML", "🦙", "service", O, "llm-self", svc(20, 1200, 1500));
  add("featurestore", "Feature store", "AI & ML", "🧮", "db", O, "", dbo(8000, 2000, 5, 10, 400, 200));
  add("spark", "Apache Spark job", "Data & analytics", "✨", "service", O, "", svc(100, 500, 300));
  add("flink", "Apache Flink", "Data & analytics", "🐿️", "service", O, "stream-proc", svc(300, 50, 250));
  add("kafkastreams", "Kafka Streams app", "Data & analytics", "🧵", "service", O, "stream-proc", svc(800, 10, 120));
  add("airflow", "Airflow scheduler", "Data & analytics", "🌬️", "service", O, "", svc(50, 300, 150));
  add("dbt", "dbt", "Data & analytics", "🧱", "service", O, "", svc(40, 400, 60));
  add("clickhouse2", "Druid / Pinot (real-time OLAP)", "Data & analytics", "📊", "db", O, "", dbo(6000, 6000, 15, 8, 500, 300));
  add("nats2", "NATS JetStream", "Messaging", "🛰️", "queue", O, "", svc(3000, 2, 90, { unit: 60 }));
  add("pulsar", "Apache Pulsar", "Messaging", "🌟", "queue", O, "stream", svc(2000, 4, 180, { unit: 130 }));
  add("activemq", "ActiveMQ", "Messaging", "🐇", "queue", O, "rabbit", svc(400, 4, 50, { unit: 50 }));
  add("redisstreams", "Redis Streams", "Messaging", "🌊", "queue", O, "", svc(2500, 2, 80, { unit: 60 }));
  add("celery", "Celery / Sidekiq workers", "Messaging", "🥬", "service", O, "", svc(200, 80, 60));
  add("minio", "MinIO", "Storage", "🪣", "store", O, "object", dbo(15000, 4000, 20, 30, 80, 0));
  add("ceph", "Ceph", "Storage", "🐙", "store", O, "object", dbo(12000, 4000, 20, 30, 90, 0));
  add("hdfs", "HDFS", "Storage", "🐘", "store", O, "", dbo(8000, 3000, 30, 40, 100, 0));
  add("nfs", "NFS share", "Storage", "📁", "store", O, "filestore", dbo(4000, 1500, 8, 12, 60, 0));
  add("zookeeper", "ZooKeeper / etcd / Consul", "Storage", "🐘", "store", O, "", dbo(10000, 1000, 3, 8, 60, 0));
  add("keycloak", "Keycloak", "Security & identity", "🔑", "service", O, "idp", svc(500, 25, 60));
  add("auth0", "Auth0 / Okta", "Security & identity", "🪪", "external", O, "", svc(200, 80, 0));
  add("oauthproxy", "OAuth2 proxy", "Security & identity", "🛂", "proxy", O, "", svc(8000, 4, 30));
  add("firewall2", "Network firewall", "Security & identity", "🧱", "limiter", O, "", svc(200000, 2, 80, { waf: true }));
  add("akamai", "Akamai", "Traffic & edge", "🌐", "cdn", O, "cdn", svc(800000, 6, 260));
  add("nat", "NAT gateway", "Networking", "🚏", "proxy", O, "", svc(50000, 1, 40));
  add("vpn", "VPN gateway", "Networking", "🔒", "proxy", O, "", svc(5000, 8, 60));
  add("directconnect", "Direct Connect / ExpressRoute / Interconnect", "Networking", "🧵", "proxy", O, "", svc(200000, 1, 300));
  add("transitgw", "Transit gateway", "Networking", "🛤️", "proxy", O, "", svc(100000, 2, 90));
  add("vpc", "VPC / VNet", "Networking", "🛜", "passive", O, "", { cost: 0, tag: "network" });
  add("subnet", "Subnet", "Networking", "▫️", "passive", O, "", { cost: 0, tag: "network" });
  add("smtp", "SMTP relay", "External", "✉️", "external", O, "", svc(500, 120, 0));
  add("sms", "SMS provider", "External", "💬", "external", O, "", svc(300, 200, 0));
  add("pushnotif", "Push notification service", "External", "🔔", "external", O, "", svc(2000, 100, 0));
  add("stripe", "Stripe / card processor", "External", "💳", "external", O, "", svc(200, 250, 0));
  add("maps", "Maps / geocoding API", "External", "🗺️", "external", O, "", svc(500, 80, 0));
  add("openai", "OpenAI-style LLM API", "AI & ML", "🤖", "external", O, "llm-api", svc(25, 1200, 0));
  return out;
});
