/* Plain-language explanation of every component: what it is and when you would use it.
 * Shown when you hover a part in the palette or a box on the canvas. */
(function (root, factory) { if (typeof module === "object" && module.exports) module.exports = factory(); else { root.LabDocs = factory(); } })(typeof self !== "undefined" ? self : this, function () {
  "use strict";
  const D = {
    // ---- basics
    client: "Where the traffic starts: users or other systems sending requests. Set how much traffic in the Traffic tab.",
    mobile: "A phone app calling your backend. Usually goes through an API gateway; mobile networks are slower and retry a lot.",
    browser: "A web browser loading pages and calling your API. Static files can be served from a CDN so they never reach your servers.",
    dns: "Turns a name like shop.com into an address. Can point users at the nearest or a healthy region.",
    cdn: "Copies of your files kept in many cities so users get them from close by. Cuts load on your servers for images, scripts and cached pages.",
    cloudflare: "A CDN plus DDoS protection and firewall in front of your site. Popular first step for any public website.",
    fastly: "A programmable CDN with very fast cache purge. Used by news, media and API-heavy sites.",
    waf: "Web application firewall: blocks attacks and bad bots (SQL injection, scraping) before they touch your app.",
    limiter: "Caps requests per second so one client or a flood cannot take the system down. Excess gets an error instead of crashing you.",
    lb: "Spreads requests across several servers and stops sending to dead ones. Put it in front of any app that runs more than one copy.",
    glb: "Load balancer across regions: sends each user to the closest healthy region and shifts traffic when a region fails.",
    apigw: "One front door for your APIs: authentication, rate limits, routing and versioning in one place.",
    ingress: "The entry point of a Kubernetes cluster: routes outside traffic to the right service by host and path.",
    nginx: "Very common web server and reverse proxy. Terminates TLS, serves static files, forwards to your apps.",
    haproxy: "High-performance load balancer for TCP and HTTP. Used where you need fine control and very low latency.",
    envoy: "Modern proxy with retries, timeouts and metrics built in. It is the engine inside many service meshes.",
    mesh: "Sidecar proxies that give every service-to-service call retries, encryption and metrics. Adds a little latency per hop.",
    app: "A generic application server running your business code. Add instances to handle more traffic.",
    java: "A Java backend (Spring style). Strong for big business logic; needs more memory and warms up slowly.",
    node: "A Node.js backend. Great for many small I/O-heavy requests, weaker for heavy CPU work.",
    python: "A Python backend. Quick to build, slower per request, so plan for more instances (or use async).",
    go: "A Go backend. Fast, light on memory, handles very many connections per server.",
    auth: "Handles logins, tokens and permissions. Every request may check it, so keep it fast and highly available.",
    search: "A service that answers search queries against an index. Reads are heavy; keep it separate from your main database.",
    notify: "Sends emails, SMS and push messages. Usually fed from a queue so a slow provider does not block users.",
    worker: "Background job runner: takes work from a queue and processes it away from the user request.",
    serverless: "A function that runs only when called and scales automatically. No servers to manage; watch cold starts and cost at high volume.",
    llmgw: "Sits in front of language models: routing, caching, rate limits and cost control across providers.",
    llm: "A language model running on GPUs. Slow (seconds per answer), expensive, and limited by how many requests fit on a GPU.",
    embed: "Turns text or images into number vectors for similarity search. Cheaper than an LLM but still GPU work.",
    vector: "Database that finds the most similar items (by meaning, not exact words). The heart of RAG and recommendations.",
    sql: "A relational database with transactions and joins. Best default for money, orders and anything that must stay consistent.",
    postgres: "PostgreSQL: powerful open-source SQL database with JSON, extensions and strong consistency.",
    mysql: "MySQL: widely used open-source SQL database, very good for read-heavy web apps with replicas.",
    mongo: "MongoDB: stores flexible JSON-like documents. Handy when data shape changes often; can scale out by sharding.",
    dynamo: "Key-value / document store that scales almost without limit at low latency. You design access patterns up front.",
    cassandra: "Wide-column database built for huge write volumes across many machines. Fast writes, limited query flexibility.",
    clickhouse: "Column database for analytics: scans billions of rows fast. Not for frequent single-row updates.",
    "search-db": "Search engine database (OpenSearch/Elasticsearch style): full-text search, filters and aggregations.",
    warehouse: "Data warehouse for reporting over huge history. Runs big queries, not thousands of small ones per second.",
    cache: "Redis-style in-memory cache: answers repeated reads in under a millisecond and protects your database.",
    memcached: "Simple in-memory cache for key-value data. Very fast, no persistence, no fancy data types.",
    dragonfly: "A Redis-compatible cache that uses all CPU cores, so one node handles far more traffic.",
    object: "Object storage for files, images and backups. Cheap and huge, but not for fast small reads and writes.",
    queue: "Holds messages until a worker is ready. Smooths spikes and lets slow work happen later.",
    sqs: "Managed queue: simple, reliable, no servers. Each message is handled by one consumer.",
    rabbit: "Message broker with flexible routing (exchanges, topics). Good for task queues and service messaging.",
    kafka: "Distributed log for very high event volumes. Many consumers can replay the same stream.",
    stream: "Ordered event stream for real-time processing (clicks, sensors, logs).",
    pubsub: "Publish once, deliver to many subscribers. Decouples the sender from everything that reacts.",
    thirdparty: "An outside API you depend on. It has its own limits and outages you cannot fix, so use timeouts and fallbacks.",
    payment: "A payment provider. Slow and strict on limits; never make users wait on it without a timeout and retry plan.",
    email: "An email delivery service. Asynchronous by nature; queue the sends.",
    metrics: "Collects numbers over time (CPU, latency, errors). Lets you see problems and set alerts.",
    logs: "Central log storage and search. Shortens the time to find what broke.",
    tracing: "Follows one request across services so you can see which hop was slow.",
    alerting: "Notifies people when metrics cross limits. Shortens how long a bad release or outage goes unnoticed.",

    // ---- AWS
    ec2: "AWS virtual machine. Full control, you patch and scale it yourself; the base building block of AWS.",
    lambda: "AWS serverless function. Scales per request, pay per use; cold starts and a 15-minute limit apply.",
    fargate: "Run containers on AWS without managing servers. You set CPU and memory per task.",
    beanstalk: "Upload your code and AWS runs it on managed servers. Easy start, less control.",
    apprunner: "Deploy a container or repo to a scaling web service with almost no setup.",
    awsbatch: "Runs queued batch jobs on managed compute, sized to the backlog.",
    stepfn: "Orchestrates multi-step workflows with retries and branching, with no glue code.",
    eks: "AWS Kubernetes worker nodes. Wire it to the deployments that run on it; pods only run if they fit.",
    asg: "A group of EC2 servers that grows and shrinks with load and replaces failed machines.",
    alb: "AWS load balancer for web traffic: routes by path or host, terminates TLS, works with containers and Lambda.",
    nlb: "AWS load balancer for raw TCP/UDP at extreme speed and static IPs.",
    "apigw-aws": "Managed API front door on AWS: auth, throttling and routing to Lambda or servers.",
    cloudfront: "AWS CDN. Caches content at edge locations and shields your origin.",
    route53: "AWS DNS with health checks and routing by latency, location or failover.",
    "waf-aws": "AWS firewall rules for web traffic: blocks common attacks and bad bots.",
    shield: "AWS DDoS protection. Absorbs huge floods before they reach you.",
    globalaccel: "Static IPs that send users over the AWS backbone to the nearest healthy endpoint.",
    s3: "AWS object storage: unlimited files, 11 nines durability. Great for images, backups and data lakes.",
    efs: "Shared network file system for many servers at once. Slower and pricier than S3.",
    ebs: "A disk attached to one EC2 server. Fast block storage for databases and boot volumes.",
    rds: "Managed PostgreSQL or MySQL on AWS. Backups, patching and failover handled for you.",
    aurora: "AWS cloud-built MySQL/PostgreSQL: faster than plain RDS, storage grows itself, up to 15 read replicas.",
    "dynamodb-aws": "AWS key-value/document database with single-digit millisecond reads at any scale.",
    documentdb: "AWS MongoDB-compatible document database, managed.",
    keyspaces: "AWS managed Cassandra-compatible database.",
    neptune: "AWS graph database for relationships (social graphs, fraud rings, recommendations).",
    timestream: "AWS time-series database for metrics and IoT readings.",
    redshift: "AWS data warehouse for large analytics queries.",
    athena: "Run SQL directly on files in S3, pay per query. No servers.",
    elasticache: "AWS managed Redis or Memcached: microsecond reads, offloads the database.",
    memorydb: "AWS Redis-compatible database that is also durable, so it can be your primary store.",
    "sqs-aws": "AWS managed queue: unlimited scale, simple and cheap.",
    sns: "AWS pub/sub: one message fans out to many queues, emails, SMS or functions.",
    kinesis: "AWS real-time data stream for clicks, logs and events at high volume.",
    msk: "AWS managed Kafka.",
    amazonmq: "AWS managed RabbitMQ or ActiveMQ for apps that already speak those protocols.",
    eventbridge: "AWS event bus: routes events between your services and SaaS tools by rules.",
    "opensearch-aws": "AWS managed OpenSearch: full-text search, log analytics and dashboards.",
    bedrock: "AWS API to use foundation models (Claude, Llama and others) without hosting GPUs.",
    sagemaker: "AWS endpoint that serves your own trained ML model on managed machines.",
    cognito: "AWS user sign-up, login and social identity for apps.",
    "kms-aws": "AWS encryption key service. Each use is a call with its own limit.",
    secretsmanager: "Stores passwords and API keys and rotates them. A security box; it carries no traffic.",
    iam: "AWS permissions: who can do what. Least-privilege is the goal; carries no traffic.",
    cloudwatch: "AWS metrics and logs. Enables monitoring so problems are noticed early.",
    "cloudwatch-alarms": "AWS alarms that page you when a metric crosses a limit.",
    xray: "AWS request tracing across services.",
    cloudtrail: "AWS audit log of every API action, for security reviews.",
    codepipeline: "AWS CI/CD pipeline that builds, tests and ships your code.",
    codebuild: "AWS managed build servers for compiling and testing.",
    codedeploy: "AWS automated deployments with rolling or blue-green rollout.",
    ecr: "AWS registry for your container images.",
    cloudformation: "AWS infrastructure as code: describe resources in a file and create them repeatably.",

    // ---- Google Cloud
    gce: "Google Cloud virtual machine. Full control; you manage patching and scaling.",
    cloudrun: "Run containers on Google Cloud that scale to zero. Very simple; good default for web services.",
    gcf: "Google Cloud serverless function triggered by requests or events.",
    appengine: "Google platform that runs your code and scales it for you.",
    gcpbatch: "Runs batch jobs on Google Cloud compute.",
    "workflows-gcp": "Orchestrates steps across Google Cloud services and APIs.",
    gke: "Google Kubernetes worker nodes. Wire it to the deployments that run on it.",
    mig: "A group of Compute Engine VMs that scales with load and heals itself.",
    cloudlb: "Google global load balancer: one anycast IP, traffic sent to the closest healthy backend.",
    "cloudlb-net": "Google load balancer for raw TCP/UDP traffic.",
    apigee: "Google API management: keys, quotas, analytics and monetisation for APIs.",
    cloudcdn: "Google CDN built into its load balancer.",
    clouddns: "Google managed DNS.",
    cloudarmor: "Google DDoS protection and firewall rules for web traffic.",
    gcs: "Google object storage for files, backups and data lakes.",
    filestore: "Google shared file system for many servers.",
    persistentdisk: "A disk attached to a Google VM.",
    cloudsql: "Google managed PostgreSQL, MySQL or SQL Server.",
    alloydb: "Google PostgreSQL-compatible database tuned for high speed and analytics.",
    spanner: "Google globally distributed SQL database with strong consistency. Scales like NoSQL, expensive.",
    bigtable: "Google wide-column database for very high throughput (time series, IoT, ads).",
    firestore: "Google document database with realtime sync; popular for mobile and web apps.",
    memorystore: "Google managed Redis for caching.",
    bigquery: "Google serverless data warehouse: SQL over terabytes, pay per query.",
    dataflow: "Google managed stream and batch data processing (Apache Beam).",
    gcppubsub: "Google global messaging: publish once, many subscribers, scales automatically.",
    cloudtasks: "Google queue for delayed or rate-limited tasks sent to your services.",
    eventarc: "Google routes events from services to your code.",
    vertex: "Google endpoint that serves your ML model.",
    gemini: "Google API for its Gemini language models, no GPU hosting needed.",
    identityplatform: "Google user sign-in and identity for apps.",
    cloudkms: "Google encryption key service.",
    secretmanager: "Google store for passwords and API keys. Carries no traffic.",
    cloudmonitoring: "Google metrics and dashboards. Enables monitoring.",
    cloudalerting: "Google alerts when metrics cross limits.",
    cloudtrace: "Google request tracing.",
    cloudlogging: "Google central logs.",
    cloudbuild: "Google CI: builds and tests your code.",
    clouddeploy: "Google managed continuous delivery to GKE and Cloud Run.",
    artifactregistry: "Google registry for container images and packages.",
    deploymentmanager: "Google infrastructure as code.",

    // ---- Azure
    azvm: "Azure virtual machine. Full control; you patch and scale it.",
    appservice: "Azure platform for web apps and APIs: deploy code, Azure runs and scales it.",
    azfunctions: "Azure serverless functions triggered by requests or events.",
    containerapps: "Azure serverless containers that scale to zero.",
    aci: "Run a container on Azure without managing servers, good for quick jobs.",
    azbatch: "Azure managed batch compute.",
    logicapps: "Azure low-code workflows connecting many services.",
    aks: "Azure Kubernetes worker nodes. Wire it to the deployments that run on it.",
    vmss: "A group of Azure VMs that scales with load.",
    appgw: "Azure web load balancer: routes by URL, TLS termination, optional firewall.",
    azlb: "Azure load balancer for raw TCP/UDP traffic.",
    apim: "Azure API management: auth, quotas, policies and analytics.",
    frontdoor: "Azure global entry point: CDN, routing and firewall at the edge.",
    trafficmanager: "Azure DNS-based traffic routing across regions.",
    azwaf: "Azure firewall rules for web traffic.",
    blob: "Azure object storage for files, backups and data lakes.",
    azfiles: "Azure shared file system.",
    azdisk: "A disk attached to an Azure VM.",
    azuresql: "Azure managed SQL Server database.",
    azpostgres: "Azure managed PostgreSQL.",
    cosmos: "Azure globally distributed multi-model database with low latency and tunable consistency.",
    azredis: "Azure managed Redis for caching.",
    synapse: "Azure analytics warehouse for large reporting queries.",
    servicebus: "Azure enterprise message queue and topics with ordering and dead-letter queues.",
    eventhubs: "Azure high-volume event stream (Kafka-like).",
    eventgrid: "Azure event routing between services.",
    azopenai: "Azure hosted OpenAI models with enterprise controls.",
    azureml: "Azure endpoint that serves your ML model.",
    entraid: "Azure identity and single sign-on (formerly Active Directory).",
    keyvault: "Azure store for secrets, keys and certificates. Carries no traffic.",
    azmonitor: "Azure metrics and logs. Enables monitoring.",
    azalerts: "Azure alerts when metrics cross limits.",
    appinsights: "Azure application performance monitoring and tracing.",
    azdevops: "Azure CI/CD pipelines, repos and boards.",
    acr: "Azure registry for container images.",
    bicep: "Azure infrastructure as code.",

    // ---- Docker and Kubernetes
    docker: "One containerised service. Packages code and dependencies so it runs the same everywhere.",
    dockerhost: "A machine that runs Docker containers. Wire it to the containers it hosts; they only run if they fit.",
    swarm: "Docker's built-in clustering: several machines run your containers together.",
    dockerregistry: "Stores container images that servers pull from when deploying.",
    compose: "A file that starts several containers together. Good for local and small deployments.",
    k8sdeploy: "Kubernetes Deployment: runs N identical pods and does rolling updates. The standard for stateless services.",
    k8ssts: "Kubernetes StatefulSet: pods with stable names and their own disks. For databases and brokers.",
    k8sds: "Kubernetes DaemonSet: one pod on every node (log agents, monitoring).",
    k8sjob: "Kubernetes Job or CronJob: runs to completion, once or on a schedule.",
    k8ssvc: "Kubernetes Service: a stable address that load-balances across pods.",
    k8singress: "Kubernetes Ingress controller: routes outside HTTP traffic into the cluster.",
    k8snodepool: "The machines a cluster runs on. Wire it to deployments; pods only run if they fit, and the autoscaler adds nodes with a delay.",
    k8scp: "The Kubernetes brain (API server, scheduler). If it is down, running pods continue but nothing changes.",
    k8shpa: "HorizontalPodAutoscaler: adds or removes pods with load. Wire it to a deployment.",
    k8spvc: "A persistent disk claimed by a pod so data survives restarts.",
    k8sconfig: "ConfigMap: settings kept outside the image so you can change them without a rebuild.",
    k8ssecret: "Secret: passwords and tokens given to pods.",
    istio: "Service mesh: encryption, retries and traffic rules between services. Powerful but adds overhead.",
    linkerd: "Lightweight service mesh focused on simplicity and low overhead.",
    helm: "Package manager for Kubernetes: install an app with one command.",
    argocd: "GitOps: the cluster follows what is in Git, so deployments are reviewable and repeatable.",

    // ---- DevOps
    githubactions: "CI/CD inside GitHub: builds, tests and deploys on every push.",
    jenkins: "Self-hosted automation server for builds and deployments, extremely flexible.",
    gitlabci: "CI/CD built into GitLab.",
    circleci: "Hosted CI/CD known for speed and easy setup.",
    terraform: "Infrastructure as code for any cloud: describe servers and networks in files, then apply them.",
    ansible: "Configures servers with simple playbooks, no agent needed.",
    pulumi: "Infrastructure as code using normal programming languages.",
    artifactory: "Stores build artifacts and packages for your team.",
    sonarqube: "Scans code for bugs and security problems before release.",
    trivy: "Scans container images for known vulnerabilities.",
    launchdarkly: "Feature flags: turn features on or off without a deploy, so you can roll back instantly.",
    prometheus: "Collects metrics from your services and powers alerts. The standard for Kubernetes monitoring.",
    grafana: "Dashboards for metrics and logs.",
    alertmanager: "Groups and routes Prometheus alerts to the right people.",
    pagerduty: "On-call scheduling and paging so an incident reaches a human fast.",
    datadog: "Hosted monitoring, logs and tracing in one product.",
    elk: "Search and analyse logs (Elasticsearch, Logstash, Kibana or OpenSearch).",
    otel: "One standard way to collect traces, metrics and logs from your code.",
    sentry: "Catches errors and crashes with stack traces, so bad releases show up fast.",
    vault: "HashiCorp Vault: central, audited store for secrets with short-lived credentials.",

    // ---- open source software
    springboot: "Java Spring Boot service: the most common enterprise backend framework.",
    dotnet: ".NET service (ASP.NET Core): fast, strongly typed, popular in enterprises.",
    rails: "Ruby on Rails: very productive for building products fast; needs more servers per request than Go or Java.",
    django: "Python Django: batteries included web framework, great for content and admin-heavy apps.",
    fastapi: "Python FastAPI: modern async API framework, good for ML-backed services.",
    nestjs: "NestJS: structured Node.js framework for large TypeScript backends.",
    laravel: "PHP Laravel: mature framework behind a large share of the web.",
    rustsvc: "Rust service: very fast and memory safe, used where efficiency matters.",
    elixir: "Elixir / Phoenix: handles millions of concurrent connections (chat, live updates).",
    kotlin: "Kotlin backend (Ktor/Spring): concise and JVM-fast.",
    grpcsvc: "A service speaking gRPC: compact, fast calls between internal services.",
    bff: "Backend for frontend: an API shaped for one client (web or mobile) that combines several services.",
    graphql: "One endpoint where clients ask for exactly the fields they need. Watch out for expensive queries.",
    wsgateway: "Holds many long-lived WebSocket connections for chat and live updates.",
    traefik: "Cloud-native proxy that finds services automatically (Docker, Kubernetes).",
    caddy: "Simple web server with automatic HTTPS.",
    kong: "Open-source API gateway with plugins for auth, limits and logging.",
    varnish: "HTTP cache placed in front of web servers to absorb repeated page requests.",
    "redis-cluster": "Redis split across many nodes so the cache scales beyond one machine.",
    hazelcast: "In-memory data grid used mostly from Java for shared cache and compute.",
    mariadb: "Open-source MySQL fork, drop-in for many web apps.",
    oracle: "Oracle Database: enterprise SQL with rich features and high licence cost.",
    sqlserver: "Microsoft SQL Server: enterprise SQL database, common with .NET.",
    sqlite: "A database in a single file. Perfect for small apps, but one writer at a time and no scaling out.",
    cockroach: "Distributed SQL that survives node and zone failures with strong consistency.",
    yugabyte: "Distributed PostgreSQL-compatible database that scales across nodes and regions.",
    tidb: "Distributed MySQL-compatible database for both transactions and analytics.",
    scylla: "Cassandra-compatible database in C++: very high throughput with low latency.",
    neo4j: "Graph database: follow relationships quickly (friends of friends, fraud paths).",
    influx: "Time-series database for metrics and sensor data.",
    timescale: "PostgreSQL extension for time-series data.",
    elasticsearch: "Distributed search and analytics engine for text search and logs.",
    solr: "Mature open-source search engine.",
    meilisearch: "Simple, fast search-as-you-type engine for product and site search.",
    pinecone: "Hosted vector database for semantic search and RAG.",
    weaviate: "Open-source vector database with built-in hybrid search.",
    qdrant: "Open-source vector database written in Rust, fast filtered search.",
    milvus: "Open-source vector database built for billions of vectors.",
    pgvector: "Vector search inside PostgreSQL: simplest choice when your data is already there.",
    agent: "An AI agent that plans steps and calls tools for the user. Give it a tool gateway with an allow-list and a human approval step for anything risky (payments, emails, deletes).",
    guardrails: "Checks what goes into and comes out of a model: blocks prompt injection, leaked secrets and personal data, and unsafe answers. Put it in front of every model call.",
    toolgw: "The only door an agent uses to call tools. It holds an allow-list, checks arguments, limits rates and logs every call, so a tricked agent cannot do anything it was not allowed to.",
    modelrouter: "Sends easy requests to a small, cheap model and hard ones to a premium model, and answers repeated questions from a cache. Often the biggest saving on AI cost.",
    approval: "Holds risky agent actions until a person approves them. Use it for money movement, outgoing messages, deletions and anything you cannot undo.",
    dlq: "Where messages go after they fail too many times, so one bad message cannot block the queue. Alert on it and replay messages after fixing the cause.",
    backup: "Scheduled snapshots and point-in-time restore for databases and storage, ideally copied to another region or account. A backup counts only after a restore has been tested.",
    mlserver: "Serves ML models (Triton, TorchServe) with batching for GPU efficiency.",
    vllm: "High-throughput server for self-hosted LLMs. Much more requests per GPU than naive serving.",
    featurestore: "Stores computed features for ML so training and serving use the same numbers.",
    spark: "Big-data processing across a cluster; batch jobs over huge datasets.",
    flink: "Real-time stream processing with exact state and windows.",
    kafkastreams: "Stream processing library running inside your own app on top of Kafka.",
    airflow: "Schedules and monitors data pipelines as code.",
    dbt: "Transforms data inside the warehouse using SQL models.",
    clickhouse2: "Real-time OLAP (Druid/Pinot style): sub-second analytics dashboards on fresh data.",
    nats2: "NATS JetStream: very light, fast messaging with persistence.",
    pulsar: "Apache Pulsar: messaging plus streaming with multi-tenant design.",
    activemq: "Classic Java message broker (JMS).",
    redisstreams: "Lightweight event stream built into Redis.",
    celery: "Background task workers (Celery, Sidekiq) fed by a queue.",
    minio: "S3-compatible object storage you run yourself.",
    ceph: "Self-hosted distributed storage for objects, blocks and files.",
    hdfs: "Distributed file system for big-data jobs.",
    nfs: "A shared network folder mounted by several servers.",
    zookeeper: "Coordination store (ZooKeeper, etcd, Consul): leader election and configuration. Small data, must stay available.",
    keycloak: "Open-source login and single sign-on server.",
    auth0: "Hosted login service (Auth0, Okta). You depend on their uptime.",
    oauthproxy: "Puts a login in front of an app that has none.",
    firewall2: "Network firewall: allows or blocks traffic by rules. Adds one more hop.",
    akamai: "Large enterprise CDN and security network.",
    nat: "Lets private servers reach the internet outward without being reachable from it.",
    vpn: "Encrypted tunnel between offices or clouds and your network.",
    directconnect: "Private dedicated line between your data centre and the cloud: stable latency, higher cost.",
    transitgw: "Hub that connects many networks so they can talk to each other.",
    vpc: "Your private virtual network in the cloud. A boundary; it carries no traffic in the model.",
    subnet: "A slice of a private network, public or private. A boundary; it carries no traffic in the model.",
    smtp: "Mail relay that delivers your emails.",
    sms: "SMS provider: pay per message, rate limited.",
    pushnotif: "Push notifications to phones (APNs, FCM).",
    stripe: "Card payments API. Handle its slowness and failures with timeouts and retries.",
    maps: "Maps and geocoding API, priced per call.",
    // ---- end-to-end pieces: Java platform, build and deploy, security and audit
    tomcat: "A Java application server (Tomcat, WildFly, JBoss) that runs your WAR/JAR. Familiar and stable; plan memory for the JVM.",
    springgw: "Spring Cloud Gateway: the front door of a Spring microservice system with routing, filters, authentication and rate limits.",
    eureka: "Service discovery: services register themselves and find each other by name instead of fixed addresses. Carries no traffic itself.",
    configserver: "Central configuration for many services so settings change without rebuilding. Carries no traffic itself.",
    gitrepo: "The Git repository (GitHub, GitLab). Every change starts here and triggers the pipeline.",
    maven: "Maven or Gradle compiles your Java code, runs unit tests and produces the JAR. The first step of the build.",
    buildserver: "The machine that runs your builds and tests (a Jenkins agent or CI runner). Add more when builds queue up.",
    deployserver: "The machine or tool that pushes a build to the environments, and the bastion through which operators reach private servers.",
    harbor: "A private container registry you run yourself, with vulnerability scanning and signing.",
    snyk: "Scans your dependencies (libraries) for known vulnerabilities and licence problems before you ship them.",
    codesign: "Signs container images and JARs so only trusted builds are allowed to run in production.",
    stagingenv: "A production-like environment where a release is tested before real users see it.",
    auditlog: "An append-only record of who did what and when (logins, changes, payments). Cannot be edited, kept for years for compliance.",
    siem: "Collects security logs from everywhere, correlates them and raises alerts (Splunk, QRadar). The security team console.",
    securityhub: "AWS view of security findings from many services in one place.",
    sentinel: "Microsoft cloud SIEM: collects logs, detects threats and helps investigate.",
    chronicle: "Google cloud SIEM for large-scale security log analysis.",
    guardduty: "AWS threat detection: spots suspicious activity (odd logins, crypto mining, data exfiltration) from logs.",
    defender: "Azure threat protection and security posture management.",
    scc: "Google Cloud security posture and threat detection dashboard.",
    awsconfig: "Records every AWS resource setting and checks it against rules (for example, no public buckets).",
    azpolicy: "Azure rules that block or flag resources that break your standards.",
    orgpolicy: "Google Cloud constraints that stop unsafe settings across all projects.",
    cloudaudit: "Google Cloud audit trail of admin actions and data access.",
    azactivity: "Azure record of who changed what in your subscription.",
    inspector: "AWS scanner that finds known vulnerabilities in servers and container images.",
    cloudhsm: "A hardware security module: keys are created and used inside tamper-proof hardware and never leave it. Expensive; for strict compliance.",
    openai: "External LLM API (OpenAI style): no GPUs to run, but you pay per token and share its rate limits.",
  };
  const CLS = { source: "Traffic source", router: "Load balancer / router", proxy: "Gateway / proxy", service: "Compute (runs code)", cache: "Cache", queue: "Queue / stream", db: "Database", store: "Storage", cdn: "CDN / edge", limiter: "Limiter / firewall", external: "Outside service", pool: "Machine pool (nodes)", passive: "Tooling (watches, carries no traffic)" };
  const PROV = { aws: "AWS", gcp: "Google Cloud", azure: "Azure", k8s: "Kubernetes", docker: "Docker", devops: "DevOps", oss: "Open source", generic: "Basic" };
  return { D, CLS, PROV };
});
