/* System design interview practice for the Architecture Lab Sandbox.
 * 45 classic questions, each with: the interviewer's ask, requirements, back-of-envelope numbers, what a strong answer mentions
 * (checked against your drawing), follow-up questions with model answers, and a strong reference design you can open.
 * Plus a cheat sheet of the concepts interviews ask about. Numbers are teaching numbers.
 */
(function (root, factory) { if (typeof module === "object" && module.exports) module.exports = factory(); else root.LabInterview = factory(); })(typeof self !== "undefined" ? self : this, function () {
  "use strict";
  const sc = (base, readPct, shape, x) => Object.assign({ base, shape: shape || "diurnal", readFrac: readPct / 100 }, x || {});
  const slo = (p95, avail, budget) => ({ p95, avail, budget });
  const Q = [];
  /* q(cat, title, ask, load{users,reads,writes,bytes,years,peakX,resp}, {ex} | {nodes,edges,scenario,slo}, func, nonfunc, concepts, follow, incident) */
  const q = (cat, title, ask, load, ref, func, nonfunc, concepts, follow, incident) => Q.push({ id: "q" + (Q.length + 1), cat, title, ask, load: Object.assign({ users: 1e6, reads: 20, writes: 1, bytes: 500, years: 5, peakX: 3, resp: 2000 }, load), ref, func, nonfunc, concepts, follow, incident: incident || { type: "dbDown", label: "The database primary fails for 5 minutes" } });
  const C = (label, why, ...needs) => ({ label, why, needs });
  const F = (question, answer) => ({ q: question, a: answer });

  // ---------------------------------------------------------------- Classic design problems
  q("Classic problems", "URL shortener (bit.ly)", "Design a service that turns long URLs into short ones and redirects visitors.", { users: 100e6, reads: 10, writes: 0.1, bytes: 500 }, { ex: "URL shortener" },
    ["Create a short link from a long URL", "Redirect a short link to the long URL", "Optional: custom aliases, expiry, click counts"], ["Redirects are very fast (p95 under 100 ms)", "Highly available: a dead link is a broken promise", "Reads outnumber writes about 100 to 1"],
    [C("Cache the hot links", "A few links get most clicks; serving them from memory takes load off the database.", "cache"), C("Read replicas", "Redirects are reads; replicas add read capacity and survive a primary failure.", "replicas"), C("A load balancer over several servers", "No single app server; stateless servers behind a balancer.", "lb"), C("Failover for the database", "Automatic promotion keeps redirects working when the primary dies.", "ha")],
    [F("How do you generate the short code?", "Encode a counter or ID in base62 (7 characters gives 3.5 trillion). Use a distributed ID generator or pre-allocated ranges per server to avoid collisions; hashing plus collision checks also works."), F("What if one link goes viral?", "That is a hot key. The cache absorbs it; add a CDN in front for redirects that can be cached for seconds."), F("How would you count clicks without slowing redirects?", "Write click events to a queue or stream and aggregate asynchronously; never block the redirect on the counter.")]);
  q("Classic problems", "Pastebin", "Design a service where users paste text and share a link.", { users: 5e6, reads: 8, writes: 0.5, bytes: 10000 }, { ex: "Pastebin" },
    ["Create a paste and get a link", "Read a paste by link", "Pastes expire"], ["Cheap storage for many small texts", "Reads dominate", "Old pastes can be deleted"],
    [C("CDN for popular pastes", "Immutable text is perfect for edge caching.", "cdn"), C("Cache in front of storage", "Most reads hit a small set of pastes.", "cache"), C("A key-value store", "Access is always by key, so a key-value database scales easily.", "nosql")],
    [F("Where do large pastes go?", "Store the text in object storage and keep metadata (id, owner, expiry) in the database."), F("How do you expire pastes?", "Store an expiry time and let a background job delete expired ones; the read path also checks the expiry.")]);
  q("Classic problems", "Rate limiter", "Design a rate limiter that protects an API from abuse.", { users: 10e6, reads: 50, writes: 0, bytes: 100 }, { ex: "Bot flood" },
    ["Limit requests per user, key or IP", "Reject extra requests with a clear error", "Different limits per plan"], ["Adds almost no latency", "Works across many servers", "Must not fail the API if it breaks"],
    [C("A rate limiter or WAF at the edge", "Shed abusive traffic before it reaches your servers.", "limiter"), C("A shared counter store (cache)", "All servers must see the same counts; Redis with atomic increments is the usual answer.", "cache"), C("A load balancer", "The limiter sits in front of a balanced server pool.", "lb")],
    [F("Which algorithm?", "Token bucket allows bursts at a steady average rate; sliding window is smoother but costs more; fixed window is cheapest but lets double bursts through at window edges."), F("What if the limiter store is down?", "Fail open (allow traffic) for most APIs, fail closed for expensive or sensitive ones; local in-memory limits are a fallback."), F("Where does it run?", "At the gateway or CDN edge for coarse limits, and in the service for per-user business limits.")],
    { type: "burst", label: "Traffic jumps by 60% for 5 minutes" });
  q("Classic problems", "News feed (Twitter)", "Design a social feed where users post and follow others.", { users: 200e6, reads: 100, writes: 2, bytes: 1000, peakX: 3 }, { ex: "Social feed (Twitter style)" },
    ["Post a message", "Follow users", "See a timeline of followed users"], ["Timeline loads in under 200 ms", "Reads are about 50 times writes", "Celebrities have millions of followers"],
    [C("Cache timelines", "Precompute each user's timeline in memory so reads are one lookup.", "cache"), C("Fan-out through a queue", "Posting pushes into followers' timelines asynchronously.", "queue"), C("A scalable NoSQL store for posts", "Huge write and read volume across many machines.", "nosql"), C("A CDN for media", "Images and video should never touch the app servers.", "cdn"), C("Autoscaling app tier", "Spikes when big events happen.", "auto")],
    [F("Fan-out on write or on read?", "On write for most users (fast reads). For celebrities, fan-out on read: merge their posts into the timeline when it is requested, because writing to 50 million timelines is too slow."), F("How do you rank the feed?", "A ranking service scores candidate posts using recency, engagement and relationship features, served from a feature store."), F("How do you handle deletes?", "Soft-delete and filter at read time; a cleanup job removes the data later.")],
    { type: "cacheFlush", label: "The timeline cache is flushed" });
  q("Classic problems", "Photo sharing (Instagram)", "Design a photo-sharing app with feeds and uploads.", { users: 100e6, reads: 80, writes: 1, bytes: 2e6 }, { ex: "Photo sharing (Instagram style)" },
    ["Upload photos", "Follow users and view a feed", "Like and comment"], ["Photos load fast worldwide", "Uploads never lost", "Reads dominate"],
    [C("CDN for photos", "Most bytes are images; serve them from the edge.", "cdn"), C("Object storage for photos", "Cheap, durable storage for large blobs; the database holds only metadata.", "object"), C("Feed cache", "Feeds are read constantly.", "cache"), C("Sharded database for metadata", "Billions of rows outgrow one database.", "shards"), C("Replicas", "Read scaling and failover.", "replicas")],
    [F("How do you store and serve different image sizes?", "Generate thumbnails and sizes asynchronously after upload (a worker fed by a queue) and serve them by URL from the CDN."), F("How do you shard the metadata?", "By user ID so one user's data lives together; be careful of hot celebrity shards."), F("How do you keep uploads reliable?", "Use resumable, chunked uploads directly to object storage with a signed URL, so your app servers do not carry the bytes.")]);
  q("Classic problems", "Chat app (WhatsApp)", "Design a one-to-one and group messaging system.", { users: 500e6, reads: 40, writes: 40, bytes: 200, peakX: 2 }, { ex: "Chat app (WhatsApp style)" },
    ["Send and receive messages in real time", "Group chats", "Delivered and read receipts", "Offline delivery"], ["Very low latency", "Hundreds of millions of open connections", "Messages must not be lost"],
    [C("WebSocket gateway tier", "Long-lived connections need a dedicated tier.", "ws"), C("A queue or log for messages", "Stores messages until the recipient is online and decouples send from delivery.", "queue"), C("Write-optimised store", "Chat is a firehose of small writes.", "nosql"), C("In-memory presence and routing", "Which server holds which user's connection is looked up in memory.", "cache")],
    [F("How does a message reach a user connected to a different server?", "Look up the user's connection server in a fast store, then forward through a message bus or direct call."), F("How do you guarantee ordering?", "Per-conversation sequence numbers, and store messages partitioned by conversation ID."), F("How do you handle offline users?", "Keep messages in the store; on reconnect the client asks for everything after its last sequence number; push notifications wake the app.")]);
  q("Classic problems", "Video streaming (Netflix)", "Design a video streaming service.", { users: 100e6, reads: 5, writes: 0.02, bytes: 500, resp: 3e6 }, { ex: "Video streaming (Netflix style)" },
    ["Browse a catalogue", "Play a video with adaptive quality", "Resume where you stopped"], ["Smooth playback worldwide", "Video bytes dwarf API traffic", "Catalogue reads are fast"],
    [C("CDN serves the video", "Video is huge and popular titles repeat: edge caches carry almost all the traffic.", "cdn"), C("Object storage for video files", "Original and encoded versions live in cheap storage.", "object"), C("Cache for catalogue and sessions", "The API tier serves small metadata quickly.", "cache"), C("A scalable database for viewing history", "Very large volumes of small writes.", "nosql")],
    [F("How is a video prepared?", "Upload, transcode into many resolutions and bitrates (segments of a few seconds), and publish a manifest so the player picks quality by bandwidth."), F("What is an Open Connect style edge?", "Place caches inside ISP networks so popular content is served from very close to the user, cutting backbone traffic."), F("How do you handle a new hit release?", "Pre-warm edges with the title before launch and use tiered caches so misses do not all reach the origin.")]);
  q("Classic problems", "Video upload site (YouTube)", "Design a site where users upload and watch videos.", { users: 200e6, reads: 20, writes: 0.05, bytes: 5e7 }, { ex: "Video upload site (YouTube style)" },
    ["Upload a video", "Watch a video", "Search, comment, recommend"], ["Uploads are processed in the background", "Playback is smooth", "Storage grows forever"],
    [C("Queue plus workers for transcoding", "Processing is slow; accept the upload, queue the work, notify when done.", "queue"), C("CDN for playback", "Serve popular videos from the edge.", "cdn"), C("Object storage", "Videos are large blobs.", "object"), C("Sharded metadata database", "Billions of videos and comments.", "shards")],
    [F("How do you deal with a failed transcode job?", "Retry with backoff, move to a dead-letter queue after a few tries, and alert."), F("How do you keep storage cost sane?", "Tier cold videos to cheaper storage and delete unused renditions.")]);
  q("Classic problems", "Ride hailing (Uber)", "Design a ride-hailing service that matches riders and drivers.", { users: 20e6, reads: 20, writes: 30, bytes: 200, peakX: 4 }, { ex: "Ride tracking (Uber style)" },
    ["Drivers report location constantly", "Riders request a ride and are matched with a nearby driver", "Live trip tracking"], ["Location updates are a heavy write stream", "Matching within seconds", "High availability"],
    [C("A stream for location updates", "Millions of small writes per second are buffered by a stream.", "queue"), C("In-memory geo index", "Nearby drivers are found in memory using a geospatial index (geohash or quadtree).", "cache"), C("A scalable store for trips", "Trip history is append heavy.", "nosql"), C("Autoscaling", "Demand spikes at rush hour.", "auto")],
    [F("How do you find nearby drivers?", "Divide the map into cells (geohash, S2, H3), keep drivers per cell in memory, and search the rider's cell and its neighbours."), F("How do you avoid double-assigning a driver?", "Use an atomic reservation (lock or compare-and-set) on the driver before offering the ride."), F("What about surge pricing?", "Aggregate supply and demand per cell in a stream processor and publish a multiplier.")]);
  q("Classic problems", "File sync (Dropbox / Google Drive)", "Design a file storage and sync service.", { users: 50e6, reads: 10, writes: 4, bytes: 1e6 }, { ex: "File sync (Dropbox style)" },
    ["Upload and download files", "Sync across devices", "Share files"], ["Never lose a file", "Large files upload reliably", "Sync notices changes quickly"],
    [C("Object storage for file blocks", "Files are split into blocks stored in cheap durable storage.", "object"), C("A database for metadata", "File trees, versions and permissions are structured data.", "sql"), C("Notification stream", "Other devices are told when something changed.", "queue"), C("Sharded metadata", "Tens of millions of users.", "shards")],
    [F("How do you save bandwidth on edits?", "Chunk files, hash each chunk, and upload only changed chunks (delta sync); deduplicate identical chunks across users."), F("How do you resolve two people editing the same file?", "Keep both versions (conflicted copy) or merge by version vectors; never overwrite silently.")]);
  q("Classic problems", "Web crawler", "Design a crawler that downloads billions of pages.", { users: 1, reads: 0, writes: 0, bytes: 100000 },
    { nodes: "s:client; sc:go inst=7; f:queue workers=8; w:worker inst=14; x:thirdparty ratio=0.9 inst=14; d:cassandra shards=1; o:object; k:cache inst=2 hit=0.6", edges: "s>sc>f>w>x, w>k, w>d, w>o", scenario: sc(4000, 20, "steady"), slo: slo(800, 99, 30000) },
    ["Crawl pages starting from seed URLs", "Extract and follow links", "Store the content", "Do not crawl the same page twice"], ["Politeness: limit requests per site", "Scales to billions of pages", "Robust to bad sites"],
    [C("A URL frontier queue", "The list of pages still to fetch is a durable queue.", "queue"), C("A deduplication cache", "Remember what you have already seen (a Bloom filter or set).", "cache"), C("Object storage for pages", "Raw content is large and rarely updated.", "object"), C("Parallel workers", "Fetching is I/O bound, so run many at once.", "auto")],
    [F("How do you stay polite?", "Keep a queue per host and rate limit per host; obey robots.txt and crawl-delay."), F("How do you avoid crawling duplicates?", "Normalise URLs, keep a seen-set (Bloom filter), and hash content to detect near-duplicate pages."), F("How do you handle spider traps?", "Limit depth and pages per domain, and detect repeating URL patterns.")]);
  q("Classic problems", "Typeahead / autocomplete", "Design search suggestions that appear as you type.", { users: 50e6, reads: 60, writes: 0, bytes: 50, peakX: 3 },
    { nodes: "c:browser; cdn:cdn; a:go inst=14 auto; k:redis-cluster inst=4 hit=0.95; s:elasticsearch replicas=1 shards=1; q:kafka workers=1; w:worker inst=1", edges: "c>cdn>a>k>s, q>w>s", scenario: sc(15000, 100, "diurnal", { skew: 3 }), slo: slo(60, 99.9, 60000) },
    ["Suggest completions for a prefix", "Rank by popularity", "Update as trends change"], ["Under 100 ms end to end", "Enormous read volume", "Freshness of minutes is enough"],
    [C("Aggressive caching", "Popular prefixes repeat constantly; cache results, even at the CDN.", "cache", "cdn"), C("A search index", "Prefix lookups are served from a specialised index.", "search"), C("Offline aggregation", "Query counts are aggregated by a background pipeline, not on the request path.", "queue")],
    [F("What data structure?", "A trie (or an index of prefixes) with the top-K results stored at each node, so a lookup is O(prefix length)."), F("How do you update it?", "Aggregate query logs offline (hourly), rebuild or patch the index, and swap it in.")]);
  q("Classic problems", "Notification system", "Design a service that sends push, SMS and email notifications.", { users: 100e6, reads: 0, writes: 3, bytes: 500, peakX: 5 }, { ex: "Push notification service" },
    ["Send to one user or millions", "Multiple channels", "Respect user preferences", "Track delivery"], ["Bursty", "A slow provider must not block others", "No duplicates"],
    [C("A queue per channel", "Decouples sending from the trigger and absorbs bursts.", "queue"), C("Workers that scale", "Delivery workers scale with the backlog.", "auto"), C("Retries with a circuit breaker", "Providers fail; retry with backoff and stop hammering a broken one.", "breaker", "retries")],
    [F("How do you avoid duplicate sends?", "Give every notification an idempotency key and check it before sending."), F("How do you send to 10 million users?", "Fan out in batches through the queue; rate limit per provider; prioritise transactional over marketing.")],
    { type: "burst", label: "Traffic jumps by 60% for 5 minutes" });
  q("Classic problems", "Ticket booking (Ticketmaster)", "Design a system to sell tickets when everyone arrives at once.", { users: 5e6, reads: 30, writes: 1, bytes: 500, peakX: 30 }, { ex: "Ticket sale (flash crowd)" },
    ["Browse events and seats", "Hold and buy seats", "No seat sold twice"], ["Huge sudden spike", "Strong consistency for seat reservation", "Fair queueing"],
    [C("A waiting queue or limiter", "Admit users at a rate the backend can serve.", "queue", "limiter"), C("A cache for browsing", "Event pages are read by everyone.", "cache"), C("A transactional database for seats", "Double-selling must be impossible.", "sql")],
    [F("How do you prevent double booking?", "Reserve the seat with an atomic update or row lock with a short expiry (hold), and confirm on payment."), F("How do you handle the spike?", "Virtual waiting room, CDN for static pages, a queue in front of checkout, and pre-scaling.")],
    { type: "surge", mag: 3, label: "Traffic triples for 5 minutes" });
  q("Classic problems", "Payment system (Stripe)", "Design a system that processes card payments.", { users: 5e6, reads: 4, writes: 3, bytes: 1000 }, { ex: "Payments platform (Stripe style)" },
    ["Create a charge", "Refund", "Webhooks to merchants", "Reconciliation"], ["Never lose or duplicate money", "Strong consistency", "Audit trail"],
    [C("A transactional SQL database", "Money needs ACID transactions.", "sql"), C("Replicas and failover", "No single database failure may stop payments.", "replicas", "ha"), C("Timeouts, retries and a breaker for the provider", "The card network is slow and outside your control.", "breaker"), C("A queue for async work", "Webhooks and reconciliation happen off the request path.", "queue")],
    [F("What is idempotency and why does it matter?", "The same request repeated (a retry) must not charge twice. The client sends an idempotency key; the server stores the first result and returns it for repeats."), F("How do you keep the ledger correct?", "Double-entry append-only ledger; never update, only add compensating entries."), F("What if the provider times out?", "Mark the payment pending, query its status later, and reconcile; never assume failure or success.")]);
  q("Classic problems", "Collaborative editor (Google Docs)", "Design a real-time collaborative document editor.", { users: 10e6, reads: 30, writes: 30, bytes: 100, peakX: 3 }, { ex: "Collaborative document editor" },
    ["Several people edit at once", "See others' cursors", "Version history"], ["Edits appear in under 200 ms", "No lost edits", "Works offline then merges"],
    [C("WebSocket tier", "Edits stream both ways.", "ws"), C("In-memory session state", "Active documents are kept hot in memory.", "cache"), C("A durable database", "Operations and snapshots are stored.", "sql")],
    [F("How do you merge concurrent edits?", "Operational Transform (a server orders operations and transforms them) or CRDTs (structures that merge without a central order)."), F("How do you scale it?", "Route all editors of one document to the same server (consistent hashing) so ordering is simple.")]);
  q("Classic problems", "Distributed cache", "Design a distributed in-memory cache like Redis Cluster.", { users: 1, reads: 0, writes: 0, bytes: 1000 },
    { nodes: "c:client; a:app inst=41 auto; p:envoy inst=1; k:redis-cluster inst=1 hit=0.9; d:postgres replicas=1 ha", edges: "c>a>p>k>d, a>d", scenario: sc(20000, 95, "diurnal", { skew: 2.5 }), slo: slo(80, 99.9, 30000) },
    ["get, set, delete with expiry", "Scales horizontally", "Survives node failure"], ["Sub-millisecond reads", "High hit rate", "Rebalancing without downtime"],
    [C("Sharded cache nodes", "Split keys across many nodes.", "cache"), C("A backing database", "A miss falls through to the source of truth.", "db")],
    [F("How do you spread keys?", "Consistent hashing with virtual nodes, so adding or removing a node moves only a small share of keys."), F("Which eviction policy?", "LRU is the usual default; LFU suits stable hot sets; TTL for freshness."), F("How do you avoid a stampede?", "Coalesce concurrent misses for one key, add jitter to TTLs, and serve stale while refreshing.")],
    { type: "cacheFlush", label: "The whole cache is flushed" });
  q("Classic problems", "Key-value store (Dynamo)", "Design a highly available distributed key-value database.", { users: 1, reads: 0, writes: 0, bytes: 1000 },
    { nodes: "c:client; a:app inst=31 auto; d:dynamo shards=4 replicas=2 ha", edges: "c>a>d", scenario: sc(15000, 70, "diurnal"), slo: slo(100, 99.99, 40000) },
    ["put and get by key", "Always writable", "Scales out"], ["Availability over strict consistency", "Predictable low latency", "Handles node loss"],
    [C("Sharding", "Partition the key space across nodes.", "shards"), C("Replication", "Copies on several nodes for durability and reads.", "replicas"), C("A NoSQL database", "Key-value access with no joins.", "nosql")],
    [F("What is CAP here?", "Dynamo-style stores choose availability and partition tolerance; conflicts are resolved later with version vectors or last-write-wins."), F("What are quorums?", "With N replicas, W writes and R reads, R + W > N gives read-your-writes on the latest data; lower values trade consistency for speed."), F("How do you repair replicas?", "Hinted handoff for short outages, anti-entropy with Merkle trees for the rest.")]);
  q("Classic problems", "Search engine", "Design full-text search over a large document collection.", { users: 50e6, reads: 10, writes: 0.2, bytes: 3000 }, { ex: "Semantic search" },
    ["Index documents", "Search by keywords", "Rank results"], ["Results in under 300 ms", "Index updates within minutes", "Scales to billions of documents"],
    [C("A search index cluster", "An inverted index maps words to documents.", "search"), C("Replicas of the index", "Search is read heavy and needs availability.", "replicas"), C("A cache", "Popular queries repeat.", "cache")],
    [F("How does an inverted index work?", "For each term, a list of documents containing it; a query intersects the lists and scores the results (TF-IDF or BM25)."), F("How do you shard it?", "By document (each shard searches its own documents and results are merged) so every query fans out to all shards.")]);
  q("Classic problems", "Metrics and monitoring", "Design a system that collects metrics and raises alerts.", { users: 1, reads: 0, writes: 0, bytes: 100 }, { ex: "Metrics platform" },
    ["Collect metrics from many servers", "Dashboards", "Alert on thresholds"], ["Heavy write volume", "Data older than a week can be summarised", "Alerts must fire even during an outage"],
    [C("A stream or queue in front", "Buffer the firehose of writes.", "queue"), C("A time-series database", "Optimised for append and range queries.", "nosql"), C("Monitoring and alerting present", "The system that watches must itself be watched.", "monitor")],
    [F("Push or pull?", "Pull (Prometheus) gives control and simple discovery; push suits short-lived jobs. Many systems use both."), F("How do you keep storage cost down?", "Downsample: keep raw data for days, minute averages for weeks, hourly for years.")]);
  q("Classic problems", "Job scheduler / task queue", "Design a system that runs delayed and recurring jobs reliably.", { users: 1, reads: 0, writes: 0, bytes: 500 },
    { nodes: "c:client; a:go inst=10 auto; q:rabbit workers=7; w:celery inst=19 auto; d:postgres replicas=1 ha; k:zookeeper", edges: "c>a>d, a>q>w>d, w>k", scenario: sc(1500, 20, "spike", { spikeX: 4 }), slo: slo(500, 99.9, 12000) },
    ["Submit a job to run now or later", "Recurring jobs", "Retries on failure"], ["No job lost", "Each job runs once (or at least once)", "Scales with backlog"],
    [C("A durable queue", "Jobs wait safely until a worker takes them.", "queue"), C("Workers that autoscale", "Add workers when the backlog grows.", "auto"), C("A database for job state", "Track status, attempts and schedules.", "sql")],
    [F("At-least-once or exactly-once?", "Queues give at-least-once; make jobs idempotent so a repeat is harmless."), F("How do you run a cron job on many servers only once?", "Use a lock or leader election (ZooKeeper, etcd, database row lock) so only one instance fires it.")]);
  q("Classic problems", "Unique ID generator", "Design a service that produces unique, roughly time-ordered IDs.", { users: 1, reads: 0, writes: 0, bytes: 8 },
    { nodes: "c:client; lb:lb ha; a:go inst=48 auto", edges: "c>lb>a", scenario: sc(30000, 0, "steady"), slo: slo(60, 99.99, 12000) },
    ["Generate IDs at very high rate", "Unique across servers", "Sortable by time"], ["No coordination on the hot path", "64-bit IDs", "Survives clock issues"],
    [C("Many stateless generators", "Each generator makes IDs on its own.", "lb", "auto"), C("A load balancer in front", "Clients reach any generator; none is special.", "lb")],
    [F("What is a Snowflake ID?", "41 bits of milliseconds, 10 bits of machine ID, 12 bits of sequence: unique per machine per millisecond with no coordination."), F("What if the clock moves backwards?", "Refuse to issue IDs until it catches up, or use the last timestamp plus one.")]);
  q("Classic problems", "Leaderboard", "Design a real-time leaderboard for a game.", { users: 20e6, reads: 20, writes: 8, bytes: 100, peakX: 3 },
    { nodes: "c:mobile; lb:lb ha; a:go inst=9 auto; k:redis-cluster inst=1 hit=0.98; d:dynamo; q:kafka workers=2", edges: "c>lb>a>k>d, a>q>d", scenario: sc(9000, 70, "diurnal", { skew: 2 }), slo: slo(60, 99.9, 30000) },
    ["Submit scores", "Show top N", "Show a player's rank"], ["Instant updates", "Millions of players", "Rank of any player in milliseconds"],
    [C("An in-memory sorted structure", "Redis sorted sets give top-N and rank in logarithmic time.", "cache"), C("Durable storage behind it", "Scores must survive a cache loss.", "db"), C("Async persistence", "Write to storage through a queue.", "queue")],
    [F("How do you rank 100 million players?", "Sorted set for the top; for the long tail, bucket scores into ranges and count players per bucket to estimate rank."), F("How do you shard it?", "By score range or by season/game, then merge for global views.")]);
  q("Classic problems", "Video conferencing (Zoom)", "Design a video meeting service.", { users: 30e6, reads: 0, writes: 0, bytes: 100 },
    { nodes: "c:client; lb:nlb; sig:wsgateway inst=1 auto; m:rustsvc inst=2 auto; k:redis-cluster inst=2 hit=0.9; d:postgres replicas=1 ha", edges: "c>lb>sig>k>d, lb>m", scenario: sc(6000, 50, "diurnal"), slo: slo(120, 99.9, 40000) },
    ["Join a meeting", "Audio and video between many people", "Chat and screen share"], ["Very low latency", "Adapts to poor networks", "Global users"],
    [C("A signalling tier with WebSockets", "Set up and manage the call.", "ws"), C("Media servers", "Forward or mix streams between participants (an SFU).", "auto"), C("Regional presence", "Place media servers close to users.", "lb")],
    [F("Peer-to-peer or server?", "Peer-to-peer for two people (WebRTC); for groups an SFU receives each stream once and forwards it, saving upload bandwidth."), F("How does it adapt to bad networks?", "Simulcast (several qualities of one stream) and bitrate adaptation; the server picks the right one per viewer.")]);
  q("Classic problems", "Multiplayer game backend", "Design the backend for an online multiplayer game.", { users: 10e6, reads: 300, writes: 300, bytes: 100, peakX: 2 }, { ex: "Multiplayer game backend" },
    ["Players join matches", "Real-time state sync", "Persistent profiles and scores"], ["Latency under 80 ms", "Cheating must be hard", "Peak evenings"],
    [C("In-memory game state", "Authoritative state lives in memory on the game server.", "cache"), C("Persistent storage behind", "Progress is saved away from the hot path.", "db"), C("Messaging between servers", "Matchmaking and events flow through a bus.", "queue")],
    [F("Why is the server authoritative?", "Clients cannot be trusted; the server validates every action, and clients only predict and display."), F("How do you reduce lag?", "Regional game servers, client-side prediction with reconciliation, and sending only state changes.")]);
  q("Classic problems", "E-commerce (Amazon)", "Design an online store with search, cart and checkout.", { users: 50e6, reads: 30, writes: 2, bytes: 2000, peakX: 5 }, { ex: "E-commerce storefront" },
    ["Browse and search products", "Cart", "Checkout and pay", "Order history"], ["Checkout is never lost", "Sales-day spikes", "Search is fast"],
    [C("CDN and cache for browsing", "Most traffic is product pages.", "cdn", "cache"), C("A search index", "Product search and filters.", "search"), C("A transactional database", "Orders and inventory need ACID.", "sql"), C("Timeouts and breakers around payment", "The payment provider must not sink checkout.", "breaker")],
    [F("How do you avoid overselling?", "Decrement inventory atomically in the database (or reserve with expiry) at checkout; treat displayed stock as approximate."), F("How do you split services?", "Catalogue, cart, orders, payments and inventory as separate services with their own data, talking through events.")]);
  q("Classic problems", "Food delivery", "Design a food delivery platform.", { users: 20e6, reads: 20, writes: 4, bytes: 1000, peakX: 4 }, { ex: "Food delivery" },
    ["Browse restaurants", "Place and pay for an order", "Track the driver"], ["Lunch and dinner peaks", "Live tracking", "Payments must be reliable"],
    [C("Cache for menus", "Menus change rarely and are read constantly.", "cache"), C("A stream for order and location events", "Orders and driver locations flow through events.", "queue"), C("A transactional database", "Orders and payments.", "sql")],
    [F("How do you assign drivers?", "Match by distance and load using a geo index; offer to the best candidate with a timeout, then the next."), F("How do you keep the ETA accurate?", "Combine restaurant preparation time, driver location and map routing, updated as events arrive.")]);
  q("Classic problems", "Vacation rentals (Airbnb)", "Design a booking platform for stays.", { users: 30e6, reads: 20, writes: 0.3, bytes: 3000 }, { ex: "Vacation rentals (Airbnb style)" },
    ["Search by place, dates and filters", "Book a stay", "Reviews and messages"], ["Search is the hard part", "No double booking", "Global"],
    [C("A search index", "Geo and filter search.", "search"), C("A transactional database for bookings", "Availability and bookings need consistency.", "sql"), C("Cache and CDN", "Listings and photos are read constantly.", "cache", "cdn")],
    [F("How do you check availability quickly?", "Keep an availability index per listing (date ranges) and re-check in the transactional database when booking."), F("How do you prevent double booking?", "A unique constraint or lock on (listing, date) inside the booking transaction.")]);
  q("Classic problems", "Social graph (Facebook friends)", "Design friend relationships and friend suggestions.", { users: 500e6, reads: 20, writes: 0.2, bytes: 100 },
    { nodes: "c:mobile; gw:apigw; a:java inst=10 auto; k:redis-cluster inst=4 hit=0.9; g:neo4j replicas=1 shards=1; d:cassandra shards=1; q:kafka workers=1; s:spark inst=1", edges: "c>gw>a>k>d, a>g, a>q>d, s>d", scenario: sc(6000, 92, "diurnal", { skew: 2 }), slo: slo(120, 99.9, 60000) },
    ["Add and remove friends", "List friends and mutual friends", "Suggest people you may know"], ["Billions of edges", "Low-latency lookups", "Suggestions can be computed offline"],
    [C("A graph or adjacency store", "Relationships are best stored as adjacency lists or in a graph database.", "nosql", "graph"), C("Cache for hot profiles", "Popular users are read a lot.", "cache"), C("Offline batch compute", "Suggestions come from batch jobs.", "queue")],
    [F("How do you find mutual friends?", "Intersect two adjacency lists; keep them sorted or use bitmaps for speed."), F("How do you shard the graph?", "By user ID, and cache the hot sets; cross-shard queries are the expensive part.")]);
  q("Classic problems", "Recommendation system", "Design product or content recommendations.", { users: 50e6, reads: 20, writes: 0.5, bytes: 200 }, { ex: "Online recommendations" },
    ["Show relevant items to each user", "Learn from behaviour", "New users and items"], ["Under 150 ms", "Models updated regularly", "Personalised"],
    [C("Candidate retrieval from a vector or index store", "Narrow millions of items to hundreds fast.", "vector"), C("A feature store", "Consistent features for training and serving.", "db"), C("Cache", "Popular results are reused.", "cache")],
    [F("Two stages?", "Retrieval (fast, approximate, many candidates) then ranking (slower model, few candidates)."), F("Cold start?", "Use popularity, content features and a little exploration until behaviour data exists.")]);
  q("Classic problems", "Ad click aggregation", "Design a system that counts ad clicks in real time.", { users: 1, reads: 0, writes: 0, bytes: 100 }, { ex: "Clickstream pipeline" },
    ["Record every click", "Aggregate per ad per minute", "Dashboards and billing"], ["Enormous write volume", "Counts must be accurate for billing", "Late data happens"],
    [C("A stream in front", "Buffer and replay clicks.", "queue"), C("A stream processor or OLAP store", "Windowed aggregation and fast queries.", "warehouse", "nosql"), C("Autoscaling ingest", "Click traffic is spiky.", "auto")],
    [F("How do you count exactly once?", "Deduplicate by click ID and use idempotent writes; stream processors with checkpoints give effectively-once results."), F("What about late events?", "Watermarks: wait a bounded time for late data, then correct with a later reconciliation batch.")]);
  q("Classic problems", "Log aggregation", "Design centralised logging for hundreds of services.", { users: 1, reads: 0, writes: 0, bytes: 300 }, { ex: "Log pipeline" },
    ["Collect logs from all services", "Search them", "Retain for weeks"], ["Never slow the application", "Handles bursts", "Cheap long-term storage"],
    [C("A buffer between producers and storage", "Absorb bursts.", "queue"), C("A search store", "Query recent logs.", "search"), C("Object storage for archives", "Cheap long retention.", "object")],
    [F("How do you keep the app fast?", "Log asynchronously to local agent, which ships in batches; drop rather than block if overloaded."), F("Retention?", "Hot in the search cluster for days, cold in object storage for months.")]);
  q("Classic problems", "API gateway", "Design an API gateway for many microservices.", { users: 20e6, reads: 40, writes: 5, bytes: 500 },
    { nodes: "c:mobile; w:waf; gw:kong inst=1 auto; l:limiter; a:auth inst=3 auto; b:java inst=4 auto; s:go inst=2 auto; k:cache inst=3 hit=0.8; d:postgres replicas=1 ha; m:prometheus", edges: "c>w>l>gw>a, gw>b>k>d, gw>s>d", scenario: sc(6000, 89, "diurnal"), slo: slo(200, 99.95, 40000) },
    ["Route requests to services", "Authenticate and authorise", "Rate limit", "Aggregate responses"], ["Adds little latency", "No single point of failure", "Observability"],
    [C("Rate limiting", "Protect services from floods.", "limiter"), C("An auth check", "Central authentication.", "gateway"), C("Multiple gateway instances", "Not a single point of failure.", "auto"), C("Monitoring", "See latency and errors per route.", "monitor")],
    [F("What are the risks of a gateway?", "It becomes a bottleneck and a single point of failure if not scaled and replicated; keep it thin and stateless."), F("How do you handle a slow service behind it?", "Timeouts, circuit breakers and fallbacks per route so one service cannot exhaust the gateway's connections.")]);
  q("Classic problems", "Content delivery network", "Design a CDN.", { users: 1, reads: 0, writes: 0, bytes: 1e6 },
    { nodes: "c:browser; d:dns; e:cdn inst=1; r:cdn inst=1; o:object; a:app inst=5 auto; m:prometheus", edges: "c>d>e>r>a, r>o", scenario: sc(20000, 100, "diurnal", { staticFrac: 0.9 }), slo: slo(80, 99.99, 40000) },
    ["Serve content from the nearest edge", "Cache and expire", "Purge on demand"], ["Very high hit rate", "Global", "Protect the origin"],
    [C("Edge and regional cache layers", "Tiered caching shields the origin.", "cdn"), C("An origin", "The source of truth for misses.", "object", "auto"), C("Geo-aware DNS", "Directs users to a nearby edge.", "lb")],
    [F("How are users routed to the nearest edge?", "Geo or latency-based DNS, or anycast where many edges share one IP and the network delivers to the closest."), F("How do you purge?", "Send purge messages to all edges (or use versioned URLs so nothing needs purging).")]);
  q("Classic problems", "Email service", "Design a bulk and transactional email sender.", { users: 10e6, reads: 0, writes: 3, bytes: 20000, peakX: 6 }, { ex: "Email newsletter service" },
    ["Send transactional and marketing email", "Track opens and bounces", "Unsubscribe"], ["Bursty", "Deliverability", "No duplicates"],
    [C("A queue", "Absorb bursts and retry.", "queue"), C("Workers that scale", "Send rate follows the backlog.", "auto"), C("Provider limits handled", "Respect rate limits of the mail provider.", "external")],
    [F("How do you improve deliverability?", "SPF, DKIM and DMARC records, warmed-up IPs, low bounce rates, and honouring unsubscribes."), F("How do you separate priority?", "Separate queues for transactional (password reset) and bulk marketing so bulk never delays critical mail.")]);
  q("Classic problems", "Stock exchange / trading", "Design a system that matches buy and sell orders.", { users: 1e6, reads: 10, writes: 5, bytes: 200, peakX: 5 },
    { nodes: "c:client; g:nlb; a:rustsvc inst=12 auto; m:rustsvc inst=8; q:kafka workers=5; d:postgres shards=9 replicas=2 ha; k:dragonfly inst=2 hit=0.95", edges: "c>g>a>k>d, a>m, m>q>d", scenario: sc(5000, 50, "spike", { spikeX: 3 }), slo: slo(40, 99.99, 60000) },
    ["Place, cancel and match orders", "Order books per instrument", "Market data feed"], ["Microsecond to millisecond latency", "Strict ordering and fairness", "Never lose an order"],
    [C("A single-threaded matching engine per instrument", "One writer per book keeps ordering trivially correct.", "auto"), C("A durable event log", "Every order is appended in sequence and can be replayed.", "queue"), C("Replicas for failover", "A hot standby replays the log.", "replicas")],
    [F("How do you scale matching?", "Partition by instrument: each order book is handled by exactly one engine, so books scale independently."), F("How do you recover after a crash?", "Rebuild the order book by replaying the event log from the last snapshot.")]);
  q("Classic problems", "Maps and navigation", "Design a maps service with routing.", { users: 50e6, reads: 10, writes: 1, bytes: 200, resp: 20000 },
    { nodes: "c:mobile; cdn:cdn; gw:apigw; r:rustsvc inst=1 auto; t:cache inst=1 hit=0.85; g:postgres replicas=1 ha; o:object; q:kafka workers=1; w:worker inst=1", edges: "c>cdn>gw>r>t>g, cdn>o[s], r>q>w>g", scenario: sc(4000, 95, "diurnal", { staticFrac: 0.5 }), slo: slo(250, 99.9, 30000) },
    ["Show map tiles", "Compute routes", "Live traffic"], ["Tiles are cached at the edge", "Routing is compute heavy", "Traffic data updates continuously"],
    [C("CDN for map tiles", "Tiles are static and popular.", "cdn"), C("Routing service that scales", "Route computation is CPU heavy.", "auto"), C("Stream for traffic updates", "Live speeds arrive as events.", "queue")],
    [F("How is routing fast on a whole country?", "Precomputed hierarchies (contraction hierarchies): shortcut edges make long routes cheap to search."), F("How do you add live traffic?", "Adjust edge weights from streamed speed data and recompute or re-rank the affected routes.")]);

  // ---------------------------------------------------------------- AI
  q("AI systems", "Chatbot with RAG", "Design a customer-support chatbot grounded on company documents.", { users: 2e6, reads: 1, writes: 0, bytes: 2000 }, { ex: "RAG chatbot on AWS Bedrock" },
    ["Answer questions from documents", "Cite sources", "Handle follow-up questions"], ["Answers in a few seconds", "GPU cost is the main bill", "No wrong or made-up answers"],
    [C("A vector database", "Retrieve the most relevant passages by meaning.", "vector"), C("A cache for repeated questions", "Many users ask the same things; skip the GPU.", "cache"), C("A limit on the model tier", "Protect the expensive model from floods.", "limiter", "gateway", "auto")],
    [F("How does RAG work?", "Chunk documents, embed the chunks into vectors, store them; at question time embed the question, fetch nearest chunks and give them to the model as context."), F("How do you reduce hallucinations?", "Require answers to cite retrieved text, refuse when nothing relevant is found, and evaluate on a test set of real questions."), F("How do you cut cost?", "Cache answers (semantic cache), use a smaller model for easy questions, and limit context size.")],
    { type: "surge", mag: 3, label: "Traffic triples for 5 minutes" });
  q("AI systems", "Self-hosted LLM service", "Design an inference service for your own language model.", { users: 1e6, reads: 3, writes: 0, bytes: 3000 }, { ex: "Self-hosted LLM with vLLM" },
    ["Serve completions", "Streaming responses", "Multiple users at once"], ["GPU utilisation is everything", "Latency to first token", "Queue rather than fail"],
    [C("A batching inference server", "Continuous batching serves many users per GPU.", "llm"), C("A gateway with limits", "Route, authenticate and protect the GPUs.", "gateway"), C("A cache", "Repeated prompts and prefixes.", "cache")],
    [F("Why batch requests?", "GPUs are efficient on many sequences at once; continuous batching keeps them busy without long waits."), F("What limits capacity?", "GPU memory for the model plus the KV cache of each active request.")]);
  q("AI systems", "ML inference platform", "Design a platform that serves many ML models at low latency.", { users: 20e6, reads: 20, writes: 0, bytes: 500 }, { ex: "ML inference platform" },
    ["Serve models by name and version", "Fetch features", "A/B test models"], ["Low latency", "Autoscale on load", "Safe rollouts"],
    [C("A model server tier", "Batching and GPU/CPU serving.", "auto"), C("A feature store", "Same features for training and serving.", "db"), C("A gateway", "Routing and versioning.", "gateway")],
    [F("How do you roll out a new model safely?", "Shadow traffic first, then a small canary, comparing metrics, with instant rollback."), F("How do you detect model drift?", "Monitor input distributions and prediction quality against fresh labels.")]);
  q("AI systems", "Fraud detection", "Design real-time fraud scoring for payments.", { users: 5e6, reads: 5, writes: 1, bytes: 500 }, { ex: "Fraud scoring" },
    ["Score each transaction before approval", "Rules plus a model", "Feedback from disputes"], ["Under 100 ms", "Never the reason payments fail", "Very high recall on obvious fraud"],
    [C("A feature store", "Recent behaviour features are fetched instantly.", "db"), C("Timeouts and fallbacks", "If scoring is slow, fall back to rules and never block payments.", "breaker"), C("A model server", "Scoring service.", "auto")],
    [F("What if the model service is down?", "Fail open or to a simple rule set according to risk policy, and alert."), F("How do you handle labels arriving weeks later?", "Store scores and features, join with chargebacks later, and retrain periodically.")]);

  // ---------------------------------------------------------------- Cloud, DevOps and reliability
  q("Cloud, DevOps & reliability", "Zero-downtime deployment", "How do you deploy a new version without downtime and roll back safely?", { users: 5e6, reads: 20, writes: 2, bytes: 500 }, { ex: "Bad release, canary plus monitoring" },
    ["Release often", "No downtime", "Instant rollback"], ["Detect a bad release within minutes", "Limit how many users see a bad release", "Database changes are compatible"],
    [C("Canary or blue-green release", "Limit the blast radius of a bad version.", "canary"), C("Monitoring and alerting", "Notice problems fast.", "monitor"), C("A load balancer", "Shift traffic between versions.", "lb")],
    [F("Rolling, blue-green or canary?", "Rolling replaces gradually and is cheapest; blue-green flips all traffic and rolls back instantly but doubles capacity; canary tests on a few percent first."), F("How do you change the database safely?", "Expand then contract: add new columns and keep both working, migrate data, switch code, remove the old columns in a later release.")],
    { type: "azOut", label: "A zone goes dark" });
  q("Cloud, DevOps & reliability", "CI/CD platform", "Design a pipeline that builds, tests and deploys code.", { users: 1, reads: 0, writes: 0, bytes: 500 }, { ex: "CI/CD with monitoring" },
    ["Build on every commit", "Run tests", "Deploy to environments"], ["Fast feedback", "Repeatable builds", "Secrets protected"],
    [C("Monitoring", "Deployments need to be watched.", "monitor"), C("Safe release strategy", "Canary or blue-green deployments.", "canary"), C("A load balanced app tier", "The thing being deployed.", "lb")],
    [F("How do you speed up builds?", "Cache dependencies, run tests in parallel, build only what changed, and use remote build caches."), F("How do you handle secrets?", "Keep them in a vault, inject at deploy time with short-lived credentials, and never commit them.")]);
  q("Cloud, DevOps & reliability", "Monitoring microservices", "How do you monitor and debug a system of many services?", { users: 10e6, reads: 20, writes: 3, bytes: 500 }, { ex: "Full observability stack" },
    ["See health of every service", "Trace one request across services", "Alert on user impact"], ["Low overhead", "Alerts are actionable", "Logs are searchable"],
    [C("Metrics, logs and traces", "The three pillars; each answers a different question.", "monitor"), C("Alerting", "Page on symptoms users feel.", "monitor")],
    [F("What are the golden signals?", "Latency, traffic, errors and saturation."), F("What is a good alert?", "One tied to an SLO burn rate that needs a human, not raw CPU thresholds.")]);
  q("Cloud, DevOps & reliability", "Autoscaling on Kubernetes", "How does your service scale under load on Kubernetes?", { users: 5e6, reads: 20, writes: 2, bytes: 500, peakX: 3 }, { ex: "Kubernetes web app with HPA" },
    ["Add pods when busy", "Add nodes when pods do not fit", "Scale down when quiet"], ["React within a minute or two", "Do not thrash", "Keep headroom for zone loss"],
    [C("An autoscaler for pods", "The HPA adds pods on CPU or custom metrics.", "auto"), C("A node pool that can grow", "Pods only run if nodes have room.", "auto"), C("Databases sized for the pod count", "More pods means more connections.", "db")],
    [F("HPA versus cluster autoscaler?", "The HPA changes the number of pods; the cluster autoscaler adds nodes when pending pods cannot be scheduled. Nodes take minutes, so keep headroom."), F("What are requests and limits?", "Requests are what the scheduler reserves; limits cap usage. Bad values cause evictions or wasted nodes.")]);
  q("Cloud, DevOps & reliability", "Disaster recovery (RPO and RTO)", "How do you design for the loss of a whole region?", { users: 10e6, reads: 20, writes: 2, bytes: 500 }, { ex: "Multi-region active-passive" },
    ["Serve users if a region is lost", "Define acceptable data loss (RPO) and downtime (RTO)", "Practise failover"], ["Automatic detection", "Data replicated across regions", "Tested regularly"],
    [C("A second region", "Independent capacity elsewhere.", "region2"), C("Replicated data", "A replica in the other region that can be promoted.", "replicas"), C("A global traffic router", "Sends users to the healthy region.", "lb")],
    [F("Active-passive or active-active?", "Active-passive is simpler and cheaper, with a failover delay and small data loss; active-active gives near-zero downtime but needs conflict handling."), F("How do you know it works?", "Run game days: fail the region on purpose and measure recovery.")],
    { type: "region", target: "us", label: "The primary region goes down" });
  q("Cloud, DevOps & reliability", "Cache stampede and hot keys", "Your cache is flushed and the database melts. What happened and how do you prevent it?", { users: 5e6, reads: 50, writes: 1, bytes: 500 }, { nodes: "c:browser; lb:lb ha; a:app inst=17 auto; k:cache inst=3 hit=0.97 coalesce; d:postgres replicas=2 ha", edges: "c>lb>a>k>d, a>d", scenario: sc(4500, 97, "steady", { skew: 2.5 }), slo: slo(200, 99.9, 12000) },
    ["Serve reads from a cache", "Survive a cold cache", "Handle one very popular key"], ["Database protected", "Recovery in minutes", "Predictable latency"],
    [C("A cache", "Serves most reads.", "cache"), C("Replicas", "Extra read capacity for the cold period.", "replicas"), C("Autoscaling", "More servers while the cache refills.", "auto")],
    [F("What is a stampede?", "Many requests miss at once and all hit the database. Fix with request coalescing, staggered TTLs, and serving stale while refreshing."), F("How do you handle a hot key?", "Replicate the key across several cache nodes, use a local in-process cache, or split the key into suffixed copies.")],
    { type: "cacheFlush", label: "The cache is flushed" });
  q("Cloud, DevOps & reliability", "Retries, timeouts and circuit breakers", "A dependency slows down and everything fails. Why and how do you stop it?", { users: 1e6, reads: 20, writes: 2, bytes: 500 }, { ex: "Circuit breaker demo" },
    ["Call an outside service safely", "Recover when it slows", "Avoid a retry storm"], ["Bounded latency", "Load does not multiply", "Graceful degradation"],
    [C("Retries with limits", "A few retries with backoff.", "retries"), C("A circuit breaker", "Stop calling a failing dependency.", "breaker"), C("Autoscaling", "Room for the extra load.", "auto")],
    [F("Why do retries cause storms?", "When a dependency slows, timeouts trigger retries, which add load, which slows it further. Use exponential backoff with jitter, retry budgets and circuit breakers."), F("What is a bulkhead?", "Separate resource pools (threads, connections) per dependency so one slow dependency cannot use them all.")],
    { type: "slowDb", label: "All databases become 4× slower" });
  q("Cloud, DevOps & reliability", "Multi-tenant SaaS", "Design a SaaS product used by thousands of customers.", { users: 2e6, reads: 20, writes: 4, bytes: 1000 }, { ex: "SaaS app (multi-tenant)" },
    ["Isolate each customer's data", "Per-customer limits", "Onboard quickly"], ["One noisy tenant must not hurt others", "Data isolation", "Cost per tenant is low"],
    [C("Rate limits per tenant", "Stop one customer using everything.", "limiter", "gateway"), C("A cache", "Reduce database load.", "cache"), C("Replicas and failover", "Reliability for all tenants.", "replicas", "ha")],
    [F("Shared database or one per tenant?", "Shared schema with a tenant ID is cheapest; schema-per-tenant or database-per-tenant gives stronger isolation and easier per-customer restore at higher cost. Big customers can get their own."), F("What is the noisy neighbour problem?", "One tenant using disproportionate resources; solve with quotas, rate limits and separate pools for heavy tenants.")]);
  q("Cloud, DevOps & reliability", "Design a cost-efficient system on AWS", "Meet the goals for the least money. What do you choose?", { users: 1e6, reads: 20, writes: 1, bytes: 500 }, { ex: "AWS cost-optimised" },
    ["Serve users reliably", "Keep the bill small", "Scale up for peaks"], ["Pay for what you use", "No idle expensive resources", "Meets the goals"],
    [C("Serverless or autoscaling compute", "No idle servers.", "auto"), C("A cache", "Cheaper than more database.", "cache"), C("A CDN for static content", "Cheap egress and offload.", "cdn")],
    [F("On-demand, reserved or spot?", "Reserved or savings plans for steady load, spot for fault-tolerant batch, on-demand for spiky."), F("Where does the money usually go?", "Compute, databases, and data transfer. Right-size, cache and keep traffic inside a region.")]);

  q("Cloud, DevOps & reliability", "Secure Java microservices platform", "Design a secure platform for Java microservices from login to database, including how it is built and deployed.", { users: 5e6, reads: 30, writes: 4, bytes: 800 }, { ex: "E-commerce platform (Java microservices)" },
    ["Users log in and call several services", "Services trust each other only through authenticated calls", "Code is built, scanned and deployed automatically"], ["No secret in code", "A vulnerable dependency is caught before release", "Everything important is logged and monitored"],
    [C("An edge firewall", "Block attacks and floods before they reach the services.", "limiter"), C("A gateway that authenticates", "One place for tokens, limits and routing.", "gateway"), C("A central identity provider", "Login, tokens and single sign-on (Keycloak, Cognito, Entra ID).", "identity"), C("A secrets manager", "Keys and passwords are injected at runtime, never in the code.", "secrets"), C("A CI/CD pipeline with scanning", "Code scan, dependency scan and image scan before anything ships.", "cicd", "scan"), C("Monitoring and logs", "You must see attacks and failures.", "monitor")],
    [F("How do services trust each other?", "Mutual TLS between services (often through a mesh) plus short-lived tokens carrying the user identity; every service checks authorisation itself."), F("How do you keep secrets out of the code?", "Store them in a vault or cloud secret manager, give each service its own role, inject them at start, rotate them, and scan repositories for leaked keys."), F("What does a secure pipeline check?", "Unit tests, static code analysis (SonarQube), dependency vulnerabilities (Snyk), container image scan (Trivy), signing of the image, and a policy that only signed images may run.")]);
  q("Cloud, DevOps & reliability", "Audit logging system", "Design a system that records every important action so that it can be investigated later and cannot be altered.", { users: 20e6, reads: 4, writes: 20, bytes: 400 }, { ex: "Audit logging system" },
    ["Every service emits audit events", "Events are stored for years", "Investigators can search and export", "Records cannot be edited or deleted"], ["Never lose an event", "Writes must not slow the business request", "Tamper evident and access controlled"],
    [C("A stream or queue in front", "Decouples services from storage and absorbs bursts.", "queue"), C("An append-only audit store", "Write once, never update; use object lock or a hash chain.", "audit", "object"), C("A search index for investigators", "Find who did what quickly.", "search"), C("Workers that scale", "Consume the stream and write to storage.", "auto")],
    [F("How do you make it tamper evident?", "Append-only storage with object lock (WORM), a hash chain where each record includes the hash of the previous one, and periodic anchoring of the latest hash in a separate system."), F("Sync or async writes?", "Async through a durable stream so a slow audit store never blocks users; but never drop events: retry and dead-letter, and alert on lag."), F("What goes into an audit record?", "Who (authenticated identity), what (action and target), when (trusted time), where (service and source address), and the outcome. Never secrets or full card numbers."), F("Retention and privacy?", "Keep for the compliance period, then delete. Personal data in logs needs minimisation and access controls; archive to cheap cold storage.")]);
  q("Cloud, DevOps & reliability", "Build and deploy platform (CI/CD server)", "Design the build and deploy setup for a team shipping a Java application many times a day.", { users: 1, reads: 0, writes: 0, bytes: 500 }, { ex: "DevSecOps pipeline, commit to production" },
    ["A commit triggers a build and tests", "Artifacts are stored and versioned", "Releases go to staging, then production, safely", "Rollback is quick"], ["Builds are repeatable and fast", "Deploys never take the site down", "Every release is traceable to a commit"],
    [C("Source control and a build server", "Central, repeatable builds instead of laptop builds.", "cicd"), C("An artifact or image registry", "Versioned, immutable outputs.", "registry"), C("Infrastructure as code", "Environments created from files, not by hand.", "iac"), C("A safe release strategy", "Canary or blue-green with fast rollback.", "canary"), C("Monitoring watching the release", "Notice a bad release within minutes.", "monitor")],
    [F("How do you speed up builds?", "Cache dependencies, run tests in parallel, build incrementally, use remote caches and more agents when the queue grows."), F("How do you make releases repeatable?", "Build once, promote the same immutable artifact through environments, and keep configuration outside the artifact."), F("How do you roll back?", "Redeploy the previous artifact (blue-green switch back or canary abort). Database changes must be backward compatible so a rollback does not need a data rollback.")]);
  q("Cloud, DevOps & reliability", "Compliant cloud landing zone", "Design an AWS (or Azure or GCP) environment that passes a security and compliance audit.", { users: 1, reads: 0, writes: 0, bytes: 500 }, { ex: "Compliance-ready cloud landing zone" },
    ["Every API action in the account is logged", "Configuration is checked against rules continuously", "Threats are detected and findings collected in one place", "Least-privilege access"], ["Logs cannot be tampered with", "Non-compliant resources are found quickly", "Keys and secrets managed centrally"],
    [C("Audit logging of cloud actions", "CloudTrail, Azure Activity Log or Cloud Audit Logs.", "audit"), C("Threat detection and a security findings hub", "GuardDuty and Security Hub style services.", "siem"), C("Secrets and key management", "No secrets in code or config files.", "secrets"), C("A WAF at the edge", "Baseline protection for public endpoints.", "limiter"), C("Monitoring and alerting", "Someone must be told.", "monitor")],
    [F("What is a landing zone?", "A pre-configured multi-account setup with guardrails: central logging, identity, network layout, policies and budgets, so every new workload starts compliant."), F("How do you enforce rules?", "Preventive controls (service control policies, organization policy) stop bad actions; detective controls (Config, Policy) find drift; both feed a central place."), F("How do you handle a compromised credential?", "Short-lived credentials, MFA, alerts on unusual API calls, quick revocation, and an incident runbook that is practised.")]);

  // ---------------------------------------------------------------- Cheat sheet
  const CHEAT = [
    ["How to answer", "The five steps", "1) Clarify requirements and scale. 2) Estimate load and storage. 3) Draw the high-level design. 4) Deep-dive on one or two hard parts. 5) Find bottlenecks and failure modes. Say your trade-offs out loud."],
    ["How to answer", "Back-of-envelope numbers", "1 day = 86,400 s (~100k). 1M requests/day is ~12 req/s. Peak is usually 2 to 5 times the average. Memory read ~100 ns, SSD read ~100 µs, same-datacentre round trip ~0.5 ms, cross-continent ~150 ms. 1 KB x 1M = 1 GB."],
    ["Scaling", "Vertical vs horizontal", "Vertical means a bigger machine: simple but limited and a single point of failure. Horizontal means more machines: needs stateless servers, a load balancer and a shared data layer."],
    ["Scaling", "Stateless services", "Keep session state out of the app server (in a cache or the client token) so any server can handle any request and instances can be added or killed freely."],
    ["Load balancing", "Algorithms", "Round robin (equal), least connections (uneven request cost), consistent hashing (sticky by key, cache-friendly), weighted (different machine sizes). Layer 4 is faster, layer 7 can route by path and header."],
    ["Caching", "Patterns", "Cache-aside (app reads and fills the cache), write-through (write both), write-back (write cache, flush later: fast but risky), refresh-ahead. Eviction: LRU, LFU, TTL."],
    ["Caching", "Problems", "Stampede (many misses at once): coalesce requests, jitter TTLs. Hot key: replicate or local cache. Stale data: short TTLs or invalidate on write. Penetration (missing keys): cache the not-found result or use a Bloom filter."],
    ["Databases", "SQL vs NoSQL", "SQL gives joins, transactions and a fixed schema: best for money and relationships. NoSQL gives easier horizontal scaling and flexible schema: best for huge simple-access workloads. Choose by access pattern, not fashion."],
    ["Databases", "Indexes", "An index speeds reads and slows writes and uses space. Index the columns you filter and sort on; a composite index follows the leftmost-prefix rule."],
    ["Databases", "Replication", "Leader-follower: writes to one leader, reads from followers (replication lag means stale reads). Multi-leader and leaderless allow writes in several places and need conflict resolution."],
    ["Databases", "Sharding", "Split data across machines by key: range (easy range queries, hot spots), hash (even spread, no range queries), directory (flexible, extra lookup). Cross-shard joins and transactions are the cost. Consistent hashing eases resharding."],
    ["Databases", "ACID and BASE", "ACID: atomic, consistent, isolated, durable transactions. BASE: basically available, soft state, eventually consistent, chosen for scale and availability."],
    ["Consistency", "CAP and PACELC", "During a network partition you choose consistency or availability. PACELC adds that even without partitions you trade latency against consistency."],
    ["Consistency", "Consistency models", "Strong (everyone sees the latest write), eventual (converges later), read-your-writes, monotonic reads, causal. Quorum: R + W > N gives strong reads."],
    ["Messaging", "Queues and streams", "A queue delivers each message to one consumer (work distribution). A log or stream keeps messages so many consumers can read and replay them (Kafka). Use them to smooth spikes and decouple services."],
    ["Messaging", "Delivery guarantees", "At-most-once (may lose), at-least-once (may duplicate: make consumers idempotent), exactly-once (effectively, via idempotency and transactions). Use dead-letter queues for poison messages and apply backpressure."],
    ["Reliability", "Retries and backoff", "Retry only idempotent operations, with exponential backoff and jitter, a maximum number of attempts and a retry budget."],
    ["Reliability", "Circuit breaker, bulkhead, timeout", "Timeout: never wait forever. Circuit breaker: stop calling something that keeps failing. Bulkhead: isolate resources per dependency. Fallback: degrade gracefully."],
    ["Reliability", "Rate limiting algorithms", "Token bucket (bursts allowed), leaky bucket (smooth output), fixed window (cheap, edge bursts), sliding window (accurate). Store counters in a shared cache."],
    ["Reliability", "Load shedding and backpressure", "When overloaded, reject low-priority work early rather than let everything time out; tell producers to slow down."],
    ["Availability", "Nines and SLAs", "99.9% is 8.8 hours of downtime a year, 99.99% is 53 minutes, 99.999% is 5 minutes. Serial dependencies multiply availability; redundancy in parallel raises it."],
    ["Availability", "SLI, SLO, SLA, RPO, RTO", "SLI is a measurement (latency, errors), SLO is your target, SLA is the promise with penalties. RPO is how much data you can lose, RTO how long you can be down."],
    ["Networking", "CDN and DNS", "A CDN serves cached content from nearby edges. DNS can route by geography, latency or health. Anycast shares one IP across many locations."],
    ["Networking", "HTTP, WebSocket, SSE, long polling", "HTTP request/response; long polling holds a request open; SSE streams server to client; WebSocket gives a two-way channel for chat and games. Each open connection costs server memory."],
    ["APIs", "REST, gRPC, GraphQL", "REST is simple and cacheable. gRPC is compact and fast for internal calls. GraphQL lets clients pick fields but needs query cost limits."],
    ["APIs", "Pagination and idempotency", "Cursor pagination is stable and fast for large sets; offset pagination gets slow. An idempotency key makes retries of a POST safe."],
    ["Security", "AuthN, AuthZ, tokens", "Authentication proves who you are; authorisation decides what you may do. Use short-lived access tokens (JWT) with refresh tokens, OAuth for delegation, TLS everywhere, and encrypt sensitive data at rest."],
    ["Observability", "Metrics, logs, traces", "Metrics show trends and drive alerts, logs give detail, traces follow one request across services. Watch latency, traffic, errors and saturation."],
    ["Deployment", "Rolling, blue-green, canary", "Rolling replaces gradually, blue-green switches all traffic between two full environments, canary sends a small share first. Feature flags decouple deploy from release."],
    ["Kubernetes", "The parts to know", "Pod (one or more containers), Deployment (N replicas and rolling updates), Service (stable address), Ingress (HTTP entry), HPA (autoscale pods), node pool and cluster autoscaler (machines), requests and limits, liveness and readiness probes."],
    ["Data", "OLTP vs OLAP, CDC", "OLTP handles many small transactions; OLAP scans huge data for analytics in a column store or warehouse. Change data capture streams database changes to other systems."],
    ["Data", "Batch, stream, lambda and kappa", "Batch processes large sets on a schedule, stream processes events as they arrive. Lambda runs both; kappa uses only a replayable stream."],
    ["Patterns", "Microservices vs monolith", "A monolith is simplest to build and deploy; microservices allow independent scaling and teams but add network calls, tracing and data consistency problems. Start simple, split when there is a reason."],
    ["Patterns", "Saga and outbox", "A saga coordinates a multi-service transaction with compensating steps instead of a distributed lock. The outbox pattern writes the event in the same database transaction as the data so nothing is lost."],
    ["Patterns", "CQRS and event sourcing", "CQRS separates the write model from read models. Event sourcing stores the sequence of changes as the source of truth; the current state is derived by replay."],
    ["Security", "Audit logs done right", "Record who, what, when, where and the outcome for every important action. Write append-only (object lock or a hash chain), send through a durable stream so it never blocks users, keep for the compliance period, restrict who can read it and never log secrets or full card numbers."],
    ["Security", "Defence in depth", "Layers: edge firewall and DDoS protection, authentication at the gateway, authorisation in every service, mutual TLS between services, encryption at rest and in transit, secrets in a vault, least-privilege roles, and monitoring on top. One layer failing should not be enough."],
    ["Security", "OWASP top risks to name", "Broken access control, injection, insecure design, misconfiguration, vulnerable components, authentication failures, integrity failures (unsigned updates), logging and monitoring gaps, request forgery. Mitigate with input validation, parameterised queries, dependency scanning and secure defaults."],
    ["Deployment", "The pipeline, step by step", "Commit, build (Maven or Gradle), unit tests, static analysis (SonarQube), dependency scan (Snyk), package a container image, scan the image (Trivy), sign it, push to a registry, deploy to staging, run integration tests, canary release to production, watch metrics, roll back automatically if they degrade."],
    ["Deployment", "Java on the cloud, end to end", "Users, DNS and CDN, WAF, load balancer, Spring Boot containers (Fargate, Cloud Run, App Service or Kubernetes) with autoscaling, a managed database with replicas, a cache, object storage, secrets manager, identity provider, logs to a central store, metrics and traces, and a pipeline that builds and deploys with infrastructure as code."],
    ["Patterns", "Consistent hashing", "Place servers and keys on a ring; a key belongs to the next server clockwise. Adding or removing a server moves only its neighbours' keys. Virtual nodes even out the load."],
  ];

  // ---------------------------------------------------------------- estimation and evaluation
  const fmt = (n) => (n >= 1e9 ? (n / 1e9).toFixed(1) + " billion" : n >= 1e6 ? (n / 1e6).toFixed(1) + " million" : n >= 1e3 ? (n / 1e3).toFixed(1) + " thousand" : String(Math.round(n * 10) / 10));
  const bytes = (n) => { const u = ["B", "KB", "MB", "GB", "TB", "PB", "EB"]; let i = 0; while (n >= 1000 && i < u.length - 1) { n /= 1000; i += 1; } return (n >= 100 ? Math.round(n) : Math.round(n * 10) / 10) + " " + u[i]; };
  function estimate(question) {
    const L = question.load, req = L.users * (L.reads + L.writes), avg = req / 86400, peak = avg * L.peakX, wps = L.users * L.writes / 86400;
    return { dailyRequests: req, avgQps: avg, peakQps: peak, writeQps: wps, readWriteRatio: L.writes > 0 ? L.reads / L.writes : null, storagePerYear: L.users * L.writes * L.bytes * 365, storageTotal: L.users * L.writes * L.bytes * 365 * L.years, peakBandwidth: peak * L.resp, years: L.years };
  }
  const EQ = { search: ["search-db", "elasticsearch", "solr", "meilisearch", "opensearch-aws"], nosql: ["dynamo", "cassandra", "mongo", "scylla", "dynamodb-aws", "cosmos", "bigtable", "firestore", "keyspaces", "documentdb", "influx", "timescale", "timestream", "clickhouse", "clickhouse2", "spanner"], graph: ["neo4j", "neptune"], warehouse: ["warehouse", "redshift", "bigquery", "synapse", "clickhouse", "clickhouse2", "athena"], vector: ["vector", "pinecone", "weaviate", "qdrant", "milvus", "pgvector", "featurestore"], llm: ["llm", "vllm", "bedrock", "gemini", "azopenai", "openai", "sagemaker", "vertex", "azureml", "mlserver"] };
  const PRED = {
    cache: (d) => d.cls === "cache", cdn: (d) => d.cls === "cdn", lb: (d) => d.cls === "router", gateway: (d) => d.cls === "proxy", queue: (d) => d.cls === "queue", limiter: (d) => d.cls === "limiter", object: (d) => d.cls === "store",
    ws: (d) => d.id === "wsgateway", monitor: (d) => !!d.monitor, external: (d) => d.cls === "external", db: (d) => d.cls === "db", search: (d) => EQ.search.includes(d.id), nosql: (d) => EQ.nosql.includes(d.id), graph: (d) => EQ.graph.includes(d.id),
    identity: (d) => ["auth", "cognito", "identityplatform", "entraid", "keycloak", "auth0", "oauthproxy"].includes(d.id), secrets: (d) => /vault|secret|key vault|kms|hsm/i.test(d.name), cicd: (d) => /ci\/cd|pipeline|actions|jenkins|gitlab|circleci|build server|codebuild|cloud build|azure devops|argo/i.test(d.name) || d.tag === "cicd",
    scan: (d) => d.tag === "security-scan", audit: (d) => d.tag === "audit" || /audit|cloudtrail|activity log/i.test(d.name), siem: (d) => d.tag === "siem" || d.tag === "threat", iac: (d) => /terraform|cloudformation|pulumi|bicep|ansible|deployment manager/i.test(d.name), registry: (d) => d.tag === "registry",
    warehouse: (d) => EQ.warehouse.includes(d.id), vector: (d) => EQ.vector.includes(d.id), llm: (d) => EQ.llm.includes(d.id), sql: (d) => d.cls === "db" && (d.eq === "sql" || ["sql", "postgres", "mysql", "mariadb", "oracle", "sqlserver", "cloudsql", "alloydb", "aurora", "rds", "azuresql", "azpostgres", "cockroach", "yugabyte", "tidb", "spanner", "pgvector"].includes(d.id)),
  };
  function hasFeature(S, doc, name) {
    const nodes = doc.nodes || [];
    if (PRED[name]) return nodes.some((n) => S.BY_ID[n.type] && PRED[name](S.BY_ID[n.type]));
    const p = (n) => n.props || {};
    if (name === "replicas") return nodes.some((n) => (S.BY_ID[n.type] || {}).cls === "db" && ((+p(n).replicas || 0) > 0 || p(n).mode === "replica"));
    if (name === "shards") return nodes.some((n) => (S.BY_ID[n.type] || {}).cls === "db" && (+p(n).shards || 1) > 1);
    if (name === "ha") return nodes.some((n) => p(n).ha || p(n).autoPromote);
    if (name === "auto") return nodes.some((n) => p(n).auto);
    if (name === "region2") return new Set(nodes.map((n) => p(n).region).filter(Boolean)).size >= 2;
    if (name === "breaker") return nodes.some((n) => p(n).breaker);
    if (name === "retries") return nodes.some((n) => (+p(n).retries || 0) > 0);
    if (name === "canary") return nodes.some((n) => p(n).deploy === "canary" || p(n).deploy === "bluegreen");
    return false;
  }
  /* Score a design against a question. `Cl` is the collapse module, `X` the examples module (for the reference). */
  function evaluate(S, Cl, graph, question, ref) {
    const checks = question.concepts.map((c) => ({ label: c.label, why: c.why, pass: c.needs.some((n) => hasFeature(S, graph, n)) }));
    const sc_ = ref.scenario, goals = ref.slo, base = S.run(graph, sc_, []); if (base.error) return { error: base.error };
    const sm = base.summary, okAvail = sm.availability * 100 >= goals.avail, okLat = sm.p95 <= goals.p95, okCost = sm.cost <= goals.budget;
    const inc = question.incident, fault = { type: inc.type, target: inc.target, mag: inc.mag, startMin: 25, durationMin: 5 };
    const ci = Cl.run(S, graph, sc_, [fault]); if (ci.error) return { error: ci.error };
    const incPts = ci.avgDuring >= 0.9 && ci.recovered ? 20 : ci.avgDuring >= 0.7 && ci.recovered ? 10 : 0;
    const chk = checks.length ? checks.filter((c) => c.pass).length / checks.length : 1;
    const score = Math.round(chk * 50 + (okAvail ? 12 : 0) + (okLat ? 9 : 0) + (okCost ? 9 : 0) + incPts);
    return { score, checks, goals: { okAvail, okLat, okCost, availability: sm.availability, p95: sm.p95, cost: sm.cost, goals }, incident: { label: inc.label, avail: ci.avgDuring, recovered: ci.recovered, verdict: ci.verdict, points: incPts }, stars: score >= 90 ? 3 : score >= 75 ? 2 : score >= 55 ? 1 : 0, verdict: score >= 90 ? "Strong answer" : score >= 75 ? "Good, with gaps" : score >= 55 ? "Getting there" : "Needs more work" };
  }
  /* The reference design of a question: {name, graph, scenario, slo}. Needs the examples module and presets. */
  function reference(S, X, presets, question) {
    const r = question.ref; let e;
    if (r.ex) { e = X.LIST.find((x) => x.name === r.ex); if (e) { const g = X.build(e, S.BY_ID); return { name: question.title, graph: g, scenario: g.scenario, slo: g.slo }; }
      const p = presets.find((x) => x.name === r.ex); if (p) { const g = p.build(); return { name: question.title, graph: g, scenario: g.scenario, slo: g.slo }; }
      throw new Error("no example named " + r.ex); }
    const g = X.build({ name: question.title, nodes: r.nodes, edges: r.edges, scenario: r.scenario, slo: r.slo }, S.BY_ID); return { name: question.title, graph: g, scenario: r.scenario, slo: r.slo };
  }
  return { QUESTIONS: Q, CHEAT, estimate, evaluate, reference, hasFeature, fmt, bytes };
});
