// Sizes every "?" of the generated platform architectures so each meets its own goals at peak traffic; writes platform_sizes.js.
// Run: node tools/size_platforms.js
const fs = require("fs"), path = require("path");
const S = require("../sim.js"), PL = require("../platforms.js"), X = require("../examples_more.js");
const sizes = {}, report = [];
for (const d of PL.DESIGNS) {
  const nodes = X.parseNodes(d.nodes), slots = []; nodes.forEach((n) => Object.keys(n.props).forEach((k) => { if (n.props[k] === "?") slots.push({ id: n.id, k }); }));
  const vals = slots.map(() => 1); let best = null;
  for (let it = 0; it < 60; it++) {
    sizes[d.name] = vals; const e = Object.assign({}, d, { sizes }), g = X.build(e, S.BY_ID), r = S.run(g, d.scenario, []); if (r.error) { report.push(["ERROR", d.name, r.error]); break; }
    const peak = {}; r.st.history.forEach((h) => Object.entries(h.nodes).forEach(([id, v]) => { peak[id] = Math.max(peak[id] || 0, v.util || 0); }));
    best = { avail: r.summary.availability, p95: r.summary.p95, cost: r.summary.cost };
    let changed = false; slots.forEach((s, i) => { const u = peak[s.id] || 0; if (u > 0.85) { vals[i] = Math.min(6000, Math.max(vals[i] + 1, Math.ceil(vals[i] * u / 0.7))); changed = true; } });
    if (!changed) break;
  }
  report.push([best && best.avail >= 0.995 && best.p95 <= d.slo.p95 && best.cost <= d.slo.budget ? "ok" : "CHECK", d.name, best ? `avail ${(best.avail * 100).toFixed(2)}% p95 ${Math.round(best.p95)}ms (goal ${d.slo.p95}) cost $${Math.round(best.cost)} (budget ${d.slo.budget})` : ""]);
}
fs.writeFileSync(path.join(__dirname, "..", "platform_sizes.js"), '/* Generated by tools/size_platforms.js: sizes for the platform architectures. */\n(function (root, f) { if (typeof module === "object" && module.exports) module.exports = f(); else root.LabPlatformSizes = f(); })(typeof self !== "undefined" ? self : this, function () { return ' + JSON.stringify(sizes) + "; });\n");
report.forEach((r) => console.log(r.join(" | ")));
